### ISSUE TITLE
Create a welcome bot for the repo.

### ISSUE THREAD

**Issue by Halix267** [akshitagupta15june/Face-X#100]
**Is your feature request related to a problem? Please describe.**
Welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request.

**Comment by Halix267** [comment]
@akshitagupta15june  Can i work on this as SWOC participant

**Comment by akshitagupta15june** [comment]
HI @Halix267 github actions are already implemented in this repo

**Comment by akshitagupta15june** [comment]
You can think of new enhancements
