### ISSUE TITLE
Implementation of welcome bot

### ISSUE THREAD

**Issue by Sloth-Panda** [akshitagupta15june/Face-X#102]
Hello there,
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time as a part of DWOC. Please assign me this issue.
For reference, kindly check out: https://github.com/apps/welcome

THANK YOU

**Comment by akshitagupta15june** [comment]
ok great assigning you

**Comment by Sloth-Panda** [comment]
pr -> #110
