### ISSUE TITLE
Add Contributors Table in README.md

### ISSUE THREAD

**Issue by samir-0711** [akshitagupta15june/Face-X#103]
Like this
![image](https://user-images.githubusercontent.com/68433936/104681444-57467900-5718-11eb-97a2-4252238e88c8.png)

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by akshitagupta15june** [comment]
ok @samir-0711 assingning you

**Comment by samir-0711** [comment]
Kindly do add the DWOC and Level label for DWOC.
And also add the easy or medium or hard label for SWOC.
Thank You
