### ISSUE TITLE
README BADGES 

### ISSUE THREAD

**Issue by akrish4** [akshitagupta15june/Face-X#105]
Hi @akshitagupta15june 

I can add nice looking readme badges and align the heading to center also 

I would be glad to work on it if you are interestedvin 

Kindly do assign me  

![readme1](https://user-images.githubusercontent.com/61831021/104693469-b8c61200-572f-11eb-888b-1d1daed1f549.PNG)

The above image is an example

**Comment by akshitagupta15june** [comment]
ok assigned it to u

**Comment by akrish4** [comment]
Kindly do add the DWOC and Level label for DWOC
and also easy or medium label for SWOC @akshitagupta15june

**Comment by akshitagupta15june** [comment]
done

**Comment by akrish4** [comment]
yes thank you @akshitagupta15june 
even SWOC also have the `easy` or `medium` and `hard` label 

Kindly add anyone label also so it gets counted towards SWOC
