### ISSUE TITLE
Create any games that can be played using face expressions

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#1081]
https://github.com/akshitagupta15june/Face-X/tree/master/Face-X-Gaming

**Comment by akshitagupta15june** [comment]
Ok assigning you

**Comment by KIET7UKE** [comment]
@akshitagupta15june I'm experienced in SparkAR, I think you should know about this. It's a platform in which we can create AR filters. So I would like to work on this.

**Comment by KIET7UKE** [comment]
Ya, I also worked on developing AI games. Kindly assign me this, I'll love to work

**Comment by KIET7UKE** [comment]
Kidly assign me this.

**Comment by akshitagupta15june** [comment]
ok assigning you @KIET7UKE

**Comment by TheNobody-12** [comment]
Hello I am SWOC 3.0 Participant Please Assign me this issue I have game which  I can contribute here.
