### ISSUE TITLE
PCA improvement

### ISSUE THREAD

**Issue by adham-nasr** [akshitagupta15june/Face-X#1082]
### optimization
I would like to change the linalg.eig() method to linalg.eigh()  method in  Recognition-Algorithms/Recognition using PCA/main.py file

**Details:** 

"eigh guarantees you that the eigenvalues are sorted and uses a faster algorithm that takes advantage of the fact that the matrix is symmetric. If you know that your matrix is symmetric, use this function."
- source: https://stackoverflow.com/questions/45434989/numpy-difference-between-linalg-eig-and-linalg-eigh

since covariance matrix is by default symmetric, eigh() computes marginally faster than eig()

**Comment by akshitagupta15june** [comment]
Ok assigning you
