### ISSUE TITLE
participants can add there name and github hande in Contribution.md

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#11]
After adding give a pull request.

https://github.com/akshitagupta15june/Face-X/blob/master/CONTRIBUTORS.md

**Comment by Pranav016** [comment]
Does this issue give any points?  😃

**Comment by akshitagupta15june** [comment]
no

**Comment by sagnik1511** [comment]
I am ready to resolve this issue #11 . Please assign me this.

**Comment by akshitagupta15june** [comment]
Hi @sagnik1511 there is no assigning you can add your name directly by forking and then giving a pr

**Comment by anurag0singh** [comment]
@akshitagupta15june  I don't have the write access to this repository so it has failed the check. Please check it if possible and review it as you wish.
I have participated in GSSOC'21

**Comment by akshitagupta15june** [comment]
@anurag0singh you have to fork this repo first
Read the contributing.md

**Comment by anurag0singh** [comment]
Yes ma'am. I have forked it already and I have added a github action workflow to it. But the greeting build run failed giving me an error msg that I don't have the write access to merge this request.

**Comment by akshitagupta15june** [comment]
GitHub action pr are not accepted in repo

**Comment by rajeshpanjiyar** [comment]
I request you to add a **level** tag to this issue, it will be a great help.

**Comment by akshitagupta15june** [comment]
hi this issue will be having no tags because there is no actual implemetation.

**Comment by rajeshpanjiyar** [comment]
As many contributors have forget to add up their name in this section due
to too many issue out there. So can it not even be level0 task or issue to
be assigned to coverup all names? I can add name and GitHub handle of all
the valuable contributors.

**Comment by akshitagupta15june** [comment]
the contributors info is already mentioned in readme so this will not be counted in any levels.

**Comment by unnati914** [comment]
hi i want to work on this

**Comment by 1anshu-56** [comment]
I want to work on this issue please assign it to me.
