### ISSUE TITLE
Documentation Improvement Facial Biometric Tutorials

### ISSUE THREAD

**Issue by Omarelsherif010** [akshitagupta15june/Face-X#1113]
**Describe the documentation you want to be improved**
I want to add a tutorials folder for OpenCV face recognition to guide me and everyone else during the implementation

This a [link ](https://docs.opencv.org/3.4/de/d27/tutorial_table_of_content_face.html)for one of them

**Comment by akshitagupta15june** [comment]
Cool you can add them , assigning you
