### ISSUE TITLE
Create website for face mask detection section using html and css

### ISSUE THREAD

**Issue by ahmedtarek26** [akshitagupta15june/Face-X#1116]
There is no website for this project and I want to add a page for the mask detection section.

**Comment by akshitagupta15june** [comment]
cool u can work on it

**Comment by akshitagupta15june** [comment]
create your folder inside this https://github.com/akshitagupta15june/Face-X/tree/master/Face-X-Web

**Comment by ahmedtarek26** [comment]
@akshitagupta15june  I created this issue in a session when I was explaining how contributors can create an issue if anyone is interested in web development and want to work on this issue assigns him

**Comment by akshitagupta15june** [comment]
Ok so u can guide the contributors
You can share this issue in discord too

**Comment by dewanshiPaul** [comment]
I want to work on it. Can I get assigned?

**Comment by akshitagupta15june** [comment]
U can work on it
