### ISSUE TITLE
Add GUI app for face recognition in videos

### ISSUE THREAD

**Issue by Vaishnavi879** [akshitagupta15june/Face-X#1118]
A GUI app accepts face image and video paths, which can be present in any location of the computer.
Image is added to saved images.
Using OpenCV, it goes through video in a window and forms a box around faces that match with saved images.
After completion of the video, a message box appears saying whether the latest added image is present in the video or not.

**Comment by Vaishnavi879** [comment]
@akshitagupta15june I would like to work on this issue, please assign it to me.

**Comment by akshitagupta15june** [comment]
ok u can work on it

**Comment by shireenchand** [comment]
@akshitagupta15june can I work on this issue?

**Comment by shireenchand** [comment]
I already have the whole code ready. Please assign me the issue so that I can make a PR

**Comment by akshitagupta15june** [comment]
ok so u can add
