### ISSUE TITLE
3D facial reconstruction based on OpenCV and DirectX

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#112]
3D face reconstruction is a fundamental Computer Vision problem of extraordinary difficulty. 

CNN architecture that performs direct regression of a volumetric representation of the 3D facial geometry from a single 2D image.

**Comment by infiniteoverflow** [comment]
I would like to contribute this , kindly assign it to me.

**Comment by akshitagupta15june** [comment]
ok assigning you

**Comment by akshitagupta15june** [comment]
are you a jwoc participant?

**Comment by infiniteoverflow** [comment]
No , sorry i am a DWOC Participant
I just noticed this was labelled for JWOC.

**Comment by infiniteoverflow** [comment]
My bad. Is it possible to contribute this as a part of DWOC ?

**Comment by akshitagupta15june** [comment]
yes you can

**Comment by infiniteoverflow** [comment]
Okay, thanks a lot !!
