### ISSUE TITLE
Create a backend for face mask detection page in Face-X website 

### ISSUE THREAD

**Issue by ahmedtarek26** [akshitagupta15june/Face-X#1122]
In this issue, you'll work with persons who work on issue #1116 after they create the front end for the page and start to create the backend.

prefer to work with a python platform Django or flask.

if you use another platform you can create the API using flask to interact with the face mask detection model. 
**Note:**
create a folder for your work inside this https://github.com/akshitagupta15june/Face-X/tree/master/Face-X-Web

Good luck, contributors

**Comment by abhijeetgupto** [comment]
Hey, I'm a GSSoc contributor. Can you please assign this to me ?

**Comment by akshitagupta15june** [comment]
You can work on it

**Comment by abhijeetgupto** [comment]
Thanks ! 
Is the front-end already developed ?

**Comment by akshitagupta15june** [comment]
no that issue is also opened, some are working on it

**Comment by TheNobody-12** [comment]
please Assign me this issue
