### ISSUE TITLE
add more tutorials related to facial biometric in the readme

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#1127]
proper documentation required

**Comment by ADITYADAS1999** [comment]
can i work with this issue ?. I am GGSoC'22 contributor

**Comment by akshitagupta15june** [comment]
u can work on it

**Comment by ADITYADAS1999** [comment]
There are total eight points are mention to facial biometric in the readme , can you suggest how many points i can add with it?

**Comment by akshitagupta15june** [comment]
you can add tutorial links like some research papers or articles all separately mentioning the topics

**Comment by ADITYADAS1999** [comment]
Okey
