### ISSUE TITLE
FACE DETECTION USING HARRCASCADES

### ISSUE THREAD

**Issue by Rishitha1234** [akshitagupta15june/Face-X#1148]
Want to detect the face using different harrcascade algorithms.

**Comment by akshitagupta15june** [comment]
u can work on it

**Comment by Rishitha1234** [comment]
I couldn't clone the repository . could you help me?

**Comment by Anshul-13J** [comment]
I would like to work on this project

**Comment by akshitagupta15june** [comment]
go for it @Anshul-13J
