### ISSUE TITLE
Github actions for project enhancements

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#115]
Before assigning let me know what kind of action will you implement in the project.

**Comment by imakash3011** [comment]
I will implement a  GitHub action for  autopep8, a tool that automatically formats Python code to conform to the PEP 8 style guide.

**Comment by akshitagupta15june** [comment]
ok assigning you

**Comment by imakash3011** [comment]
I'm getting "Error: Resource not accessible by integration" in making PR. what to do?

**Comment by akshitagupta15june** [comment]
Please send the link

**Comment by akshitagupta15june** [comment]
@imakash3011

**Comment by imakash3011** [comment]
https://github.com/akshitagupta15june/Face-X/pull/140  @akshitagupta15june

**Comment by akshitagupta15june** [comment]
@imakash3011 Resources are depreciated so tests cant be carried out

**Comment by imakash3011** [comment]
Now what should I do @akshitagupta15june ? so that my PR get merged?

**Comment by akshitagupta15june** [comment]
I will see to it and will try to resolve issue.
Will let you know!

**Comment by imakash3011** [comment]
okay thank you @akshitagupta15june

**Comment by sagnik1511** [comment]
Hello @akshitagupta15june  I want to work in this repo. Please assign this to me.

**Comment by imakash3011** [comment]
https://github.com/actions/first-interaction/issues/10  do read this @akshitagupta15june . I think this "Resource not accessible by integration" problem is from GitHub itself .

**Comment by akshitagupta15june** [comment]
Hi @imakash3011 yes i got it i have to close this issue and pr.
Sorry for this even i didn't know this.
You can look for different issues I will surely assign you.

**Comment by imakash3011** [comment]
Okay no problem @akshitagupta15june .
