### ISSUE TITLE
Adding details about ResNet50 in readme

### ISSUE THREAD

**Issue by shatakshisingh24** [akshitagupta15june/Face-X#120]
Hi! As we are using different algorithms for Face recognition, it will be helpful if there will be a description of the architecture in readme of that folder. 

I can add description of Resnet50 in readme of that folder. Later we can do this for all CNN architectures used.

**Comment by shatakshisingh24** [comment]
@akshitagupta15june please assign me this issue if this can be done here. I would like to do as a part of DWOC

**Comment by akshitagupta15june** [comment]
Hi @shatakshisingh24 here is resnet 50 Implementation
https://github.com/akshitagupta15june/Face-X/tree/master/Recognition%20using%20ResNet50

You can add details in its readme

**Comment by akshitagupta15june** [comment]
Are you a swoc participant?

**Comment by shatakshisingh24** [comment]
I have participated in DWOC.

**Comment by shatakshisingh24** [comment]
Thanks for assigning. I will do this by evening

**Comment by akshitagupta15june** [comment]
great!!

**Comment by akshitagupta15june** [comment]
HI @shatakshisingh24 I am adding gssoc label here because dwoc is now over!
