### ISSUE TITLE
Add slop 2.0 logo in engaging and collaboration in readme file

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#1222]
![image](https://user-images.githubusercontent.com/57909583/192081238-88466c68-afb5-481c-8edd-22f0d9ea4dea.png)

**Comment by cyrilckurian** [comment]
hello ,i would like to work on this issue, can you assign this to me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
as you are workin on hacktoberfest issue @ArshErgon i am assigning this issue to @cyrilckurian

**Comment by cyrilckurian** [comment]
> as you are workin on hacktoberfest issue @ArshErgon i am assigning this issue to @cyrilckurian 

I am participating in hacktoberfest , will create PR after Oct 1st
