### ISSUE TITLE
Add hacktoberfest logo in engaging and collaboration in readme file

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#1223]
![image](https://user-images.githubusercontent.com/57909583/192081377-e6fb4b35-4874-499c-b688-baeac77242cb.png)

**Comment by cyrilckurian** [comment]
hello ,i would like to work on this issue can you assign this to me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
ok

**Comment by sceary-expert** [comment]
Can you provide the link of the readme file you are talking about?

**Comment by ArshErgon** [comment]
@akshitagupta15june why that image was not good? #1224

**Comment by akshitagupta15june** [comment]
actually i already added the image in the issue if you have seen and also the picture you added was not aligned and was in wrong place it should be in engaging and collaboration

**Comment by ArshErgon** [comment]
@akshitagupta15june yeah I saw that, but I thought you have put that as a reference, and I put it on the top so that it will the first thing visible to the user because the engaging & coll, if way too down. Anyway no problem will make a new branch and will give you a PR for this issue #1222

**Comment by akshitagupta15june** [comment]
assigning you @ArshErgon

**Comment by akshitagupta15june** [comment]
@cyrilckurian i have assigned you the other issue

**Comment by ArshErgon** [comment]
@akshitagupta15june  I just saw that eng & coll using a single png file for displaying it inline, so I also have to edit that single png file and add the hacktoberfest logo inside that? or just add the logo inside the eng & coll with same height and width as others?
