### ISSUE TITLE
add a cool snapchat or insta filter for Diwali, Dussehra using opencv

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#1228]
Makesure that the filter is not already available in this folder https://github.com/akshitagupta15june/Face-X/tree/master/Snapchat_Filters
![image](https://user-images.githubusercontent.com/57909583/192432974-a33127c9-7603-4a99-85a0-64193977dcc3.png)

**Comment by Riddhiman-M** [comment]
Hi! I would like to work on this enhancement issue, can you please assign this to me @akshitagupta15june ?

**Comment by akshitagupta15june** [comment]
Anyone can work on this no need of assigning

**Comment by Sumedha4** [comment]
Hi! I would like to work on this. I wanted to ask if its necessary that the filters must be diwali related?

**Comment by Sumedha4** [comment]
Hi! I would like to work on this. I wanted to ask if its necessary that the filters must be diwali related? @akshitagupta15june

**Comment by nerdy-nakul** [comment]
Can i still work on this issue, there is SWOC tag in it.

**Comment by akshitagupta15june** [comment]
yes @nerdy-nakul
