### ISSUE TITLE
Recognition using ensemble learning

### ISSUE THREAD

**Issue by Adarsh88** [akshitagupta15june/Face-X#123]
**Is your feature request related to a problem? Please describe.**
Adding facial recognition using ensemble learning

**Describe the solution you'd like**
Ensemble learning uses OpenFace, DeepFace, FaceNet and VGG-Face to recognize faces more effectively.

**Approach to be followed (optional)**
The image will be trained using the four combined models and Cosine, Euclidean, Euclidean L.2 will be taken to accurately predict 2 faces. It can also predict if a given face is in a folder. 

Please attach SWOC label in this issue. Thanks in advance.

**Comment by akshitagupta15june** [comment]
hi thankyou for generating the issue!
Are you a dwoc participant?
