### ISSUE TITLE
Face Recognition Using Principal Component Analysis Implementation

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#124]
PCA is a statistical approach used for reducing the number of variables in face recognition. In PCA, every image in the training set is represented as a linear combination of weighted eigenvectors called eigenfaces. These eigenvectors are obtained from covariance matrix of a training image set.

Other Algorithms Implementation

https://github.com/akshitagupta15june/Face-X/tree/master/Recognition-Algorithms

**Comment by keshavdalmia25** [comment]
can i work on this

**Comment by keshav2508** [comment]
can i work on this

**Comment by akshitagupta15june** [comment]
yes!
assigning you

**Comment by mehabhalodiya** [comment]
Can I work on this issue? Can you assign me as there is no progress by the assigned member?
