### ISSUE TITLE
YouTube Controller

### ISSUE THREAD

**Issue by MihirRajeshPanchal** [akshitagupta15june/Face-X#1309]
A youtube video controller made using opencv and pyautogui to navigate through video using hand gestures

**Comment by MihirRajeshPanchal** [comment]
@akshitagupta15june I have raised a PR for this issue : https://github.com/akshitagupta15june/Face-X/pull/1310

**Comment by MihirRajeshPanchal** [comment]
This PR is FOR SWOC S3 Hackathon

**Comment by akshitagupta15june** [comment]
hey @MihirRajeshPanchal try to implement it using facial blink or mouth expression but not hand because as it a repo for face related operations

**Comment by MihirRajeshPanchal** [comment]
@akshitagupta15june I have raised a PR for the same : https://github.com/akshitagupta15june/Face-X/pull/1324
