### ISSUE TITLE
CI/CD: Format Python Code

### ISSUE THREAD

**Issue by deadex-ng** [akshitagupta15june/Face-X#1318]
**Is your feature request related to a problem? Please describe.**
We're receiving python code from different contributors, which means different developers format the code differently.

**Describe the solution you'd like**
We should have a standard format for the code. I suggest we use [black](https://github.com/psf/black)
We can have a workflow for this. Once a contributor opens a PR, we check the code format.

**Describe alternatives you've considered**
I suggest we use [black](https://github.com/psf/black). It's a very popular code formatter.

**Approach to be followed (optional)**
We can have a workflow for this. Once a contributor opens a PR, we check the code format.

**Additional context**
I would like to work on this issue for SWC season 3

**Comment by deadex-ng** [comment]
@akshitagupta15june I'd like to work on this.

**Comment by rafiya2003** [comment]
I would like to contribute in it

**Comment by elle-Bee** [comment]
Hey @akshitagupta15june can I work on this issue under the SSOC?

**Comment by Garvanand** [comment]
@akshitagupta15june please assign this issue to me
