### ISSUE TITLE
GCA-Gender Classification API

### ISSUE THREAD

**Issue by CrispenGari** [akshitagupta15june/Face-X#1332]
**Gender Classification API**
I propose to contribute to `FaceX` with a deep learning `API` called "GCA" which is a simple REST API for classifying the gender of a human being based on facial features. 

<img src="https://github.com/CrispenGari/gender-classification/raw/main/faces.jpg" alt="cover" width="100%"/>

**Served as a GraphQL and REST API**
Given an image of a human face, the API should be able to classify the gender of the image based on the facial features with `~95.1%` accuracy. The API will exist in two endpoints on a `flask` local server that will be running on port `3001` which can be configured during starting the server script. The endpoints will be:

```
http://127.0.0.1:3001/api/gender - REST

- OR
http://127.0.0.1:3001/graphql - GraphQL
```

Request can be send to the server using different API `clients` for example using `cURL` you can classify the gender by sending the following request to the server.

```shell
curl -X POST -F image=@male.jpg http://127.0.0.1:3001/api/gender
```
The expected response from the server will be as follows:

```json
{
  "predictions": {
    "class": "male",
    "label": 1,
    "meta": {
      "description": "classifying gender based on the face of a human being, (vgg16).",
      "language": "python",
      "library": "tensforflow: v2.*",
      "main": "computer vision (cv)",
      "programmer": "@crispengari"
    },
    "predictions": [
      {
        "class": "female",
        "label": 0,
        "probability": 0.019999999552965164
      },
      {
        "class": "male",
        "label": 1,
        "probability": 0.9800000190734863
      }
    ],
    "probability": 0.9800000190734863
  },
  "success": true
}
```

**Comment by akshitagupta15june** [comment]
Go for it @CrispenGari
