### ISSUE TITLE
Adding a new ESRGAN model for facial image super Resolution

### ISSUE THREAD

**Issue by lakkidivinay01** [akshitagupta15june/Face-X#1364]
**Is your feature request related to a problem? Please describe.**
Want to add a model which works best on facial images.

**Describe the solution you'd like**
Building a ESRGAN model from [https://www.tensorflow.org/hub/tutorials/image_enhancing](https://www.tensorflow.org/hub/tutorials/image_enhancing). 

**Describe alternatives you've considered**
If this model doesn't work then work as good then we can consider other GAN models such as real-ESRGAN.

**Additional context**
![image](https://user-images.githubusercontent.com/86817867/219939392-300f5106-0247-41a3-b118-1d6326ee970f.png)

**Comment by akshitagupta15june** [comment]
go for it
