### ISSUE TITLE
Add some cool snapchat filters which are not already present in repo

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#1419]
![image](https://github.com/akshitagupta15june/Face-X/assets/57909583/85f90b61-d59b-42d9-a7a7-f6853b668b3f)

**Comment by why-sid** [comment]
Please assign this issue to me

**Comment by s0oraj** [comment]
Hi @akshitagupta15june , iam a SSOC23 contributer and I would like to resolve this issue

Can you assign me this issue? Or any other issues you might have?
Heres My Resume which you might find useful: [Resume](https://github.com/s0oraj/Animus/files/11521330/Resume.pdf)
Here is my background in ML:

1) 6 months plus experience in working under college professors for research project on medical image classification.
2) Got 228 global rank in Amazon ML Challenge 2023 out of 30000+ teams participating.
3) Experienced with trainig machine Learning Models. Including image preprocessing techniues such as histrogram equilization, augmentation, stationary wavelet transformation, image segmentation. Along with feature extraction from models like resnet50 inceptionv3 vgg16 etc

Looking forward to hear from you.

**Comment by preetimahto17** [comment]
Hello! I'm really excited about this project. I would love to contribute and work on it. Could you kindly assign the project to me? I'm confident that I can make a valuable contribution.

**Comment by bhoomigupta1406** [comment]
Hey @akshitagupta15june  i would like to contribute under GSSOC Contributor.

**Comment by Viswaraje** [comment]
Hello @akshitagupta15june  please assign this issue to me as a GSSOC contributor. I am very much willing to contribute on this issue.

**Comment by Courage003** [comment]
hey @akshitagupta15june I want to explore this field and thats why would love to contribute in this portion

**Comment by iamrohanmane** [comment]
hey @akshitagupta15june i love to work on this project can you assign me

**Comment by mitali-dxt** [comment]
Hey @akshitagupta15june I would love to contribute and work on this under SSOC'23. I am a beginner to open source, and this would be a good issue apply what i learned in python and face detection.

**Comment by Siddharth015** [comment]
Hey @akshitagupta15june I am interested in contributing on this issue under SSOC 2.0.  I would love to add some coolest Snapchat filters in the project.

**Comment by Shubhisingh921** [comment]
Hello @akshitagupta15june  
I am Shubhi Singh a technology enthusiast and first time participating in SSOC with the wish to be contributing towards 'Face-X'.
I have participated in Snap AR Hackathon and also have huge interest in making new and unique snapchat filter. 
Kindly Assign this issue to me.

**Comment by garay-3** [comment]
Hello @akshitagupta15june 
I am a participant in SSOC 2.0 and I would very much like to get my hands in contributing to open source by starting with this issue. I am a beginner but I do have a clear knowledge in python and I am sure that I can learn whatever is required for developing snapchat filters and bring to you with the best outcome. So kindly please assign me with this task.
Thank you

**Comment by Sanjay71013** [comment]
Hey @akshitagupta15june, I would like to add a "Comic Book Speech Bubbles" snapchat filter that would Place comic-style speech bubbles with popular phrases like "Wow!" or "OMG!" near the user's face. Hoping you will assign me this task.
Thank you!

**Comment by Insiyaya** [comment]
Hello @akshitagupta15june  I would like to contribute to this issue being a SSOC'23 contributor, Please assign me this issue as it is very interesting to learn more about this
