### ISSUE TITLE
Deploy it as a webapp using Django

### ISSUE THREAD

**Issue by dishamodi0910** [akshitagupta15june/Face-X#1425]
Django is known for its simplicity. It also allows us to use the other javascript frameworks along with it. 
It would be easier to implement.

**Comment by FutureRising007** [comment]
Can you please specify as of what do we have to deploy as a webapp ??

**Comment by dishamodi0910** [comment]
We will have to generate some of the pickle files and update templates and static folders for the UI of the website.
And we are done.

**Comment by FutureRising007** [comment]
I can try that ma'am. Please do assign me this task , and do let me know where and how the pickle files are to be added.

**Comment by hkcs1206** [comment]
I am also interested to work on this issue, If possible assign it to me ma'am.

**Comment by Anushka20365** [comment]
Hello @akshitagupta15june  ,
I'm Anushka Anand . I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.I have worked on a number of projects using Django and I will try my best to contribute to this,in the best way possible. 

Skills
HTML5, CSS3, JS, Bootstrap | Python, Django | Php, mysql | MERN | Responsive Design | Adobe Photoshop |


Can you please assign this issue to me.

**Comment by A15h** [comment]
I would like to work on this issue and I have deployed a number of projects using flask and Django. I would like to request you to please assign this issue to me.

**Comment by dishamodi0910** [comment]
Should we all collab??

**Comment by hkcs1206** [comment]
I have no problem, count me in.

**Comment by gurltech** [comment]
@dishamodi0910 yes totally, I am happy to collab and put my tech stack to use

**Comment by akshitagupta15june** [comment]
right now website is not completed to be deployed
