### ISSUE TITLE
Increase the Accuracy of Facial Emotion Recognition model

### ISSUE THREAD

**Issue by Rishi-11-2** [akshitagupta15june/Face-X#1436]
I would like to increase the accuracy of facial emotion recognition model and propose different models. I would also like to train the model on the Affectnet Dataset.
Different Models Include :
1: Custom Model in which there are 7 layers
2: Inception_V3 Model Fine-Tuned for facial Recognition

**Comment by sijalalyy** [comment]
I am GSSOC 23 contributor assign this to me i want to work on this

**Comment by reshma045** [comment]
Hello, I'm GSSoC'23 Contributor. Please assign me this issue. I want to work on this and contribute to this.

**Comment by akshitagupta15june** [comment]
assigned
