### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by the-amazing-atharva** [akshitagupta15june/Face-X#1437]
I would like to be assigned for GSSOC'23 for this issue

Suggestions:
+ Restructuring the header for a more visually appealing look
+ other minor changes

**Comment by akshitagupta15june** [comment]
is it regarding website?

**Comment by the-amazing-atharva** [comment]
Regarding README.md @akshitagupta15june

**Comment by akshitagupta15june** [comment]
what changes u want to add?

**Comment by the-amazing-atharva** [comment]
@akshitagupta15june 
![image](https://github.com/akshitagupta15june/Face-X/assets/121221252/30557ff1-28fa-4944-a5fa-c54e889f6e1f)
.
.
.
![image](https://github.com/akshitagupta15june/Face-X/assets/121221252/4992f5bf-c594-4f1b-bac2-6ae0e5287a97)
.
.
.
I have more changes in mind, is this fine?

**Comment by akshitagupta15june** [comment]
its not required currently
