### ISSUE TITLE
Feature request -Face authentication through OpenCV

### ISSUE THREAD

**Issue by poorvika11** [akshitagupta15june/Face-X#1439]
**Is your feature request related to a problem? Please describe.**

- Authentication through face is a major problem due to its low level accuracy. I would like to make a model which recognise the face and authenticate the face for high level privacy and authentication.
- As per the areas suggested to work-on in Face-X README, this project will work on the areas of different algorithm to recognise face and biometric.

**Describe the solution you'd like**
I want to make a program that will be used to authenticate the face thorugh OpenCV. Also thinking to add some new features to it also.

**Describe alternatives you've considered**
I am thinking to add some features to it like authenticating the face through facial epressions/emotions as well. Detection, recognisation, authenticating the facial context of the person.

**Additional context**
It could be used for high level security purposes by authenticating the face and also by emotions.

**Comment by akshitagupta15june** [comment]
its already present in repo
