### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kinshukgoel4** [akshitagupta15june/Face-X#1447]
**Is your feature request related to a problem? Please describe.**
Hey I cannot see the folder of the famous algorithm YOLO- You only look once 

**Describe the solution you'd like**
I would like to make a folder using YOLO

**Describe alternatives you've considered**
I have considered making version wise folder so it will be easy to navigate

**Additional context**
https://pjreddie.com/darknet/yolo/

**Comment by akshitagupta15june** [comment]
already present check in recognition algo folder
