### ISSUE TITLE
Addressing Skin Type Classification in Facial Recognition : Normal / Oily / Dry

### ISSUE THREAD

**Issue by riyasachdeva04** [akshitagupta15june/Face-X#1448]
**Is your feature request related to a problem? Please describe.**
 Incorporating skin type classification into facial recognition systems can provide valuable information for personalized skincare and cosmetic recommendations.  By accurately identifying whether a person's skin is oily, normal, or dry, the system can provide tailored suggestions, such as recommending specific moisturizers, cleansers, or cosmetics that are suitable for their skin type. This integration can enhance the user experience and assist individuals in maintaining optimal skincare routines.

**Describe the solution you'd like**
 The solution should be able to seamlessly integrate with existing facial recognition pipelines and provide the skin type classification as an additional output.A robust machine learning model, such as a convolutional neural network (CNN), will be employed for training and inference. 

This issue is being submitted for GSSOC'23

**Comment by akshitagupta15june** [comment]
already present in repo

**Comment by riyasachdeva04** [comment]
could not find it

**Comment by riyasachdeva04** [comment]
@akshitagupta15june
