### ISSUE TITLE
Add a new snapchat filter

### ISSUE THREAD

**Issue by NKNaN** [akshitagupta15june/Face-X#1452]
* I would like to add a new snapchat filter with some dynamic feature. The filter is a pair of cat ears, and it has some shaking effect when we detect eye-close and eye-open.

* The solution is simple: First, detect the height of eyes in a frame and compare it to that in previous frames, if the height increase then mark as an eye-open event, otherwise an eye-close event. Next according to eye-open or eye-close event, rescale the height of masking image (ear cats) in current frame. When eyes open, upscale the height masking image; when eyes close, downsize the height of masking image.

\* The filter image is different from any existing filter images in the current repo.

**Comment by akshitagupta15june** [comment]
already present
