### ISSUE TITLE
Improvement of CONTRIBUTING.md file 📄

### ISSUE THREAD

**Issue by kinshukgoel4** [akshitagupta15june/Face-X#1464]
**Is your documentation request related to a problem? Please describe.**
Hey, I'm in GSSOC'23 and I was looking at the [CONTRIBUTING.md](https://github.com/akshitagupta15june/Face-X/blob/master/CONTRIBUTING.md) file and I feel it needs improvement

**Describe the documentation you want to improve**
For starters we need to have a specific pipeline for the work hence changing the git checkout and git commit statements is required. I can also make other adjustments/changes to improve documentation and make it more beginner-friendly

**Additional context**
After changes, it will look something like this @akshitagupta15june 
![image](https://github.com/akshitagupta15june/Face-X/assets/98045941/7ee3c665-de7d-485e-b8ef-2de21345c7b8)
Please assign me this task, add the gssoc label to the issue/PR

**Comment by akshitagupta15june** [comment]
ok go for it but i can see metadatengine in the commands so please make it according to moksh

**Comment by kinshukgoel4** [comment]
Sure I will . That screenshot was just a example
