### ISSUE TITLE
Documentation Improvement for Emoji-based-Emotion-prediction

### ISSUE THREAD

**Issue by Ribli0308** [akshitagupta15june/Face-X#1467]
**Is your documentation request related to a problem? Please describe.**
The readme.md file of emoji-based-emotion-prediction has some spelling mistakes and grammatical errors. Additionally it can be made beginner friendly by adding installation and getting started guidelines. 

**Describe the documentation you want to improve**
I will implement the above mentioned changes in the document.
@akshitagupta15june please assign this document to me.
I am in GSSOC'23.

**Comment by devkakeri06** [comment]
I'd like to help you with this. Please assign me this issue.

**Comment by yukta28** [comment]
I can work on the documentation part please assign me this so I can improve the language and make all the necessary corrections.
