### ISSUE TITLE
A feature to count the blink of an eye using opencv and python. We can also add many features in it later on. This will be a good Project to do on .

### ISSUE THREAD

**Issue by Abhishantpadam** [akshitagupta15june/Face-X#1473]
**Is your feature request related to a problem? Please describe.**
Yes ir is related to a problem. Many people stare at the screen and forgets to blink.

**Describe the solution you'd like**
I would like to count the no. of blink.

**Additional context**
we can also extend this project to count the blink of more than 1 person.

Name -  Abhishant Padam
Participant  of SSOC 2023.

**Comment by 072arushi** [comment]
@Abhishantpadam the issue has been assigned
