### ISSUE TITLE
Feature request: Designing a website for Face-X

### ISSUE THREAD

**Issue by yaten2302** [akshitagupta15june/Face-X#1493]
Feature Idea:

Hi @akshitagupta15june, I was thinking that designing a website for the repository "Face-X" would be a great idea?

Here the details of all the algorithms with some demo screenshots and videos can be added with a small description of the project.
The "Home Page" will contain the description of the project, in the "Projects section" 

![image](https://github.com/akshitagupta15june/Face-X/assets/129659514/7e45902a-3122-4f80-b5f2-5793cbd6de1c)
all these can be added with a beautiful design.

Also there can be a "Contact Page" and "FAQs Page".

Please assign this task to me under GSSOC'23 as I want to work on it 🙏 .

**Comment by Aditya-Lawate-codez** [comment]
Hi @akshitagupta15june , I want to contribute, I would be making a Materialistic UI for your website kindly, assign me this

**Comment by Courage003** [comment]
Hi @akshitagupta15june mam, I would love to contribute in making a perfectly looked UI deisgn along with the coded frontend part of website to me. Please assign me this under SSOC'2023

**Comment by KritikaRawat** [comment]
Hi @akshitagupta15june, this project really appeals to me and I would love to be part of this. Using the HTML, CSS and Js , with animations(of course) I want to create a appealing face for the FaceX

**Comment by kadambari68** [comment]
@yaten2302 are you interested in doing work in collaboration I can create the signup, login, contact page, etc, or any other page like the about us page, you can review the designs for them as I am proficient in HTML, CSS, and JavaScript, and know ReactJs

**Comment by Courage003** [comment]
If anyone up for collab with me....I am also eager to join

**Comment by Palakkgoyal** [comment]
We all will give our best but let Akshita decide whom she will assign

**Comment by swastik-akhil** [comment]
It's a similar issue to issue #1485 
Please note that a similar issue to this has already been raised and I'm working under it because it was already assigned to me.
Kindly refer to the screenshot below.
![Screenshot (175)](https://github.com/akshitagupta15june/Face-X/assets/126651810/e425391e-3f75-486e-a9a9-16da5c7e9ca4)

**Comment by Palakkgoyal** [comment]
@swastik-akhil But, it would not be feasible to assign a whole frontend to a single person, it should be divided into different pages and also using HTML and CSS it would be very messy to manage all these algorithms, instead we all should participate in making of this. But ok, it's assigned to you so it's your choice

**Comment by arpy8** [comment]
I would like to contribute on this issue

**Comment by TanyaNegi10** [comment]
I also want to contribute on this issue

**Comment by HadiaSamreen** [comment]
Hi I am Hadia Samreen. I would love to join you all as a team to contribute to this issue.
