### ISSUE TITLE
Documentation Improvement for Face-Emotions-Recognition [SSOC Project Request]

### ISSUE THREAD

**Issue by meaviral17** [akshitagupta15june/Face-X#1502]
**Problem**
The documentation provided in this repo folder is very lengthy and poorly formatted. 
A lengthy documentation may be difficult to navigate and consume, especially if it is not well-organized or if it contains irrelevant information. Users might have difficulty finding the information they need, and this can lead to frustration and confusion.
It is also visually unappealing, making it hard to read and understand. The lack of proper formatting, such as headings, bullet points, and tables, can make it difficult to locate specific information and follow the document's structure.
Both of these issues can negatively affect the usability of the documentation, which can reduce the effectiveness of the project Face-X.

**Improvements**
- Simplification of the language.
- Using headings and subheadings.
- Using bullet points.
- Including tables for technical specifications.
- Providing links to relatable resources.

**Conclusion**
I want to raise this issue and work on it @akshitagupta15june . I am a SSOC 2.0 Contributor.

**Comment by meaviral17** [comment]
Please Ma'am assign me this issue under SSOC'23

**Comment by meaviral17** [comment]
@akshitagupta15june ma'am please assign the issue as part of SSOC 2.0 ...

**Comment by TanyaNegi10** [comment]
I also want to contribute on this issue

**Comment by meaviral17** [comment]
@akshitagupta15june Please merge this PR. It solves the issue as discussed above. I am Aviral Srivastava, a SSOC Contributor. Please add SSOC label as well.
Thank you.
