### ISSUE TITLE
Request to adding Snapchat Filter with Funny Eyeballs and Dragon Flame using OpenCV and Python

### ISSUE THREAD

**Issue by pra9patil** [akshitagupta15june/Face-X#1504]
Hi Akshita Gupta Ma'am

I am excited about contributing to this open-source project! After going through the project details, I noticed that there's an opportunity to add a Snapchat filter with funny eyeballs and a dragon flame coming from the mouth. I believe this addition will bring a lot of entertainment and creativity to the project.

Motivation:
Snapchat filters have become increasingly popular, and I believe that by incorporating funny eyeballs and a dragon flame, we can make the user experience even more enjoyable. It will provide users with a fun and interactive way to transform their appearance while adding an element of fantasy.

Proposed Approach:
To implement this Snapchat filter, I suggest leveraging the power of OpenCV and Python. OpenCV provides robust computer vision capabilities, making it suitable for detecting facial features and applying digital effects.

Facial Feature Detection: I will utilize OpenCV's face detection algorithms to identify the location of the user's face accurately.

Funny Eyeballs Overlay: Using image manipulation techniques available in OpenCV, I will create a set of funny eyeball overlays. These overlays will be aligned with the user's eye coordinates, making them appear as if the user has funny eyeballs.

Dragon Flame Effect: I will design a dragon flame effect using image processing techniques. By analyzing the user's mouth region, I will apply the flame effect, giving the illusion that the user is exhaling dragon fire.

Implementation Plan:

Set up the development environment by installing OpenCV and the necessary Python libraries.
Develop the facial detection module to identify and track the user's face.
Create a library of funny eyeball overlays and implement the eye alignment functionality.
Implement the dragon flame effect by analyzing the user's mouth region and applying the appropriate image processing techniques.
Integrate the filter into the existing Snapchat project structure, ensuring it works seamlessly with other filters.
Write unit tests to validate the functionality and performance of the new filter.
Document the code and provide clear instructions for other developers to understand and extend the filter if needed.

Request for Feedback:
I would appreciate any feedback or suggestions regarding the proposed approach. If you have any specific guidelines, coding conventions, or best practices that I should follow while working on this feature, please let me know. Additionally, if there are any existing code snippets, resources, or design references that could be helpful, I would be grateful to receive them.

I am really looking forward to contributing to this project and working on this exciting Snapchat filter!

Best regards,
Pranav Patil

**Comment by pra9patil** [comment]
Please Ma'am assign me this issue  under SSOC'23

**Comment by akshitagupta15june** [comment]
go for it! but try to look for diffrent filters which are not already present in repo

**Comment by pra9patil** [comment]
Okk ma'am thank you!
