### ISSUE TITLE
Add a funny snapchat filter 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#1509]
make sure they are not already available in snapchat folder in repo

![image](https://github.com/akshitagupta15june/Face-X/assets/57909583/63186d81-9afc-4b18-b2cb-9c326b94248d)
![image](https://github.com/akshitagupta15june/Face-X/assets/57909583/eeacbd02-9e5e-4b56-ad9a-7c613e9516a6)

No need to assign anyone
Everyone can work on this

**Comment by ayan-joshi** [comment]
okay lesgo this seems interesting

**Comment by Insiyaya** [comment]
Hello @akshitagupta15june I would like to contribute to this issue being a SSOC'23 contributor, Please assign me this issue as it is very interesting to learn more about this

**Comment by ayan-joshi** [comment]
@akshitagupta15june I will add a snapchat filter with lipstick please assign me this issue I'm a GSSOC and SSOC contributor

**Comment by Lavi211215** [comment]
I want to make a filter that will make everybody laugh please assign me this issue

**Comment by Raksha703** [comment]
Hey, I am SSOC'23 contributer and want to work on this issue using openCV. Pleases assign it to me as I already created some of them.
