### ISSUE TITLE
[GSSOC'23] Face Detection using OpenCV

### ISSUE THREAD

**Issue by Tanya-1109** [akshitagupta15june/Face-X#1510]
**Is your feature request related to a problem? Please describe.**
A program to detect any face moving in and out of video frames for any amount of time.

**Describe the solution you'd like**
We will create a program that detects the face and calculate the amount of time it was out of the webcam and then store the time in a csv file.

**Describe alternatives you've considered**
I have used openCV in this module but we can also consider using PIL or Deep Learning for more accuracy.

**Approach to be followed (optional)**
We will be using various frames in black and white as well as coloured to detect any motion . 

**Additional context**
A new file times.csv will be formed the first time we run the program and and it gets updated everytime . We will have to press q to exit the webcam.

**Comment by Tisha6661** [comment]
could you please assign me this task.
