### ISSUE TITLE
Feature request (Makeup Detection on face)

### ISSUE THREAD

**Issue by Shreyg-27** [akshitagupta15june/Face-X#1542]
**Is your feature request related to a problem? Please describe.**
So, this project basically aims at recognizing whether a person has applied makeup or not.

**Describe the solution you'd like**
So with an input image, the project will be able to detect whether a person has done makeup or not. 

**Approach to be followed (optional)**
I have decided to work on this using TensorFlow and Keras. 

I have raised this issue under gssoc'23.

**Comment by 072arushi** [comment]
@Shreyg-27 assigned
