### ISSUE TITLE
auto-capture selfies by detecting a smile

### ISSUE THREAD

**Issue by Killer2OP** [akshitagupta15june/Face-X#1555]
**Describe the solution you'd like**
I came across this advertisement for Oppo — the phone automatically captures a selfie when the beautiful actress smiles at the camera. This seemed like a pretty easy challenge given the wonderful dlib library from Python.

**Approach to be followed**
A simple python app to take a selfie automatically using webcam when it detects a smile

**Comment by aaviiothic** [comment]
please assign me the issue!!!!

**Comment by akhilmishra365** [comment]
this is a pretty easy 6task please assign me this issue

**Comment by NARAYANAM-SAITEJASWI** [comment]
I want to work on this issue please assign it to me
