### ISSUE TITLE
Helmet Detection

### ISSUE THREAD

**Issue by Killer2OP** [akshitagupta15june/Face-X#1556]
**Is your feature request related to a problem? Please describe.**
In Industry, specially manufacturing industry, Personal Protective Equipment (PPE) like helmet (hard-hat), safety-harness, goggles etc play a very important role in ensuring the safety of workers. However, many accidents still occur, due to the negligence of the workers as well as their supervisors. Supervisors can make mistakes due to the fact that such tasks are monotonous and they may not be able to monitor consistently.

**Describe the solution you'd like**
This project aims to utilize existing CCTV camera infrastructure to assist supervisors to monitor workers effectively by providing them with real time alerts.

**Approach to be followed (optional)**
-> Input is taken from CCTV cameras
-> YOLO is used for detecting persons with proper PPE and those without PPE.
-> Deep_SORT allocates unique ids to detected persons and tracks them through consecutive frames of the video.
-> An alert is raised if a person is found to be without proper PPE for more than some set duration, say 5 seconds.

**Comment by impeccable16** [comment]
I want to work on this issue

**Comment by Parthiv-01** [comment]
I want to work on this issue
