### ISSUE TITLE
Eye Blink Counter

### ISSUE THREAD

**Issue by ayon037** [akshitagupta15june/Face-X#1566]
**Is your feature request related to a problem? Please describe.**
-- I want to create a system that could be stopped through the eye blinks of the user.

**Describe the solution you'd like**
-- The system would detect the eye blink counts of the user. Whenever it detects a double blink of the user, the system will be stopped.

**Describe alternatives you've considered**
-- The alternatives can be through voice commands. A 'stop' command would also be applicable.

**Approach to be followed (optional)**
-- I'll use the Opencv python library to detect the eye blinks.

Please assign this issue to me. In addition, I'm a GSSOC'23 open source contributor.

**Comment by akshitagupta15june** [comment]
hey this is not required as it is already implemented
