### ISSUE TITLE
Add a new snapchat filter (Halo and Sparkle)

### ISSUE THREAD

**Issue by akriti44** [akshitagupta15june/Face-X#1572]
**Related issues or bug**
-Halo filter with motion sparkle using openCV, dlib and imageio, under GSSOC'23.
Fixes: #1229 

**Proposed changes**
-Add a snapchat filter

**Additional info**
-imageio: Used for reading the GIF file.
-The code utilizes the shape predictor model (shape_predictor_68_face_landmarks.dat) for detecting faces and their landmarks.

**Preview**
<img src="https://github.com/akshitagupta15june/Face-X/assets/92203588/7d190b96-932a-4ef2-8e8e-886ba258cc8b" width="400" height="300" alt="Face Filters Preview">

**Comment by MohanaSrinivas** [comment]
Please assign this issue to me, I will do my best for this
