### ISSUE TITLE
Adding Readme for Facial Reconstruction

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#159]
Creation of a proper readme file for explanation of face reconstruction and adding the already included implementation of Joint 3D Face Reconstruction details
https://github.com/akshitagupta15june/Face-X/tree/master/Face%20Reconstruction

**Comment by infiniteoverflow** [comment]
@akshitagupta15june I would like to work on adding this !!

**Comment by smriti1313** [comment]
Hi, Can I do this under DWoC ?
Kindly let me know.
Thank you

**Comment by akshitagupta15june** [comment]
yes you can

**Comment by smriti1313** [comment]
hey, Can i add gifs in readme?

**Comment by akshitagupta15june** [comment]
yes you can
