### ISSUE TITLE
Readme Improvement in face detection folder

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#160]
Add a comparative study of implemented algorithms for face detection 
https://github.com/akshitagupta15june/Face-X/tree/master/Face-Detection

**Comment by mehabhalodiya** [comment]
Please assign this to me @akshitagupta15june

**Comment by anirudhsai20** [comment]
Hi @akshitagupta15june. Can you please assign this to me under SWOC ?

**Comment by akshitagupta15june** [comment]
Hi this issue pr is already made
Its need to be reviewed
