### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by LeeRenJie** [akshitagupta15june/Face-X#163]
A logo based on:
![image](https://user-images.githubusercontent.com/67599130/106491604-009bb600-64f2-11eb-8ccc-8372b91f0cf9.png)

**Comment by LeeRenJie** [comment]
Please assign this to me under DWOC thank you!

**Comment by akshitagupta15june** [comment]
Hi @LeeRenJie .
Happy to assign you

**Comment by LeeRenJie** [comment]
Thanks. I will be sending drafts here before creating a PR.

**Comment by LeeRenJie** [comment]
<img width="299" alt="Face-X logo" src="https://user-images.githubusercontent.com/67599130/106631950-36a36d80-65b8-11eb-9f5e-f29882d66a79.png">
My first attempt. Any comments?

**Comment by LeeRenJie** [comment]
<img width="361" alt="Screenshot 2021-02-03 143239" src="https://user-images.githubusercontent.com/67599130/106708168-5fb21580-662d-11eb-8013-f4451d70dcb0.png">
<img width="360" alt="Screenshot 2021-02-03 143821" src="https://user-images.githubusercontent.com/67599130/106708243-7eb0a780-662d-11eb-9f27-527bb21280d8.png">
Second attempt
