### ISSUE TITLE
3D Face Reconstruction using Graph Convolutional Networks

### ISSUE THREAD

**Issue by infiniteoverflow** [akshitagupta15june/Face-X#164]
**Is your feature request related to a problem? Please describe.**
This code is related to the Face Reconstuction section.

**Describe the solution you'd like**
This code is a solution to the research paper https://arxiv.org/pdf/2003.05653.pdf , which seeks to reconstruct the 3D facial shape with high fidelity texture from a single image, without the need to capture a large-scale face texture database.

**Approach to be followed (optional)**
The shapes and coarse textures are from https://github.com/microsoft/Deep3DFaceReconstruction, the GCNs code is based on https://github.com/anuragranj/coma and mesh processing libraries from https://github.com/MPI-IS/mesh.

**Comment by infiniteoverflow** [comment]
@akshitagupta15june I would like to work on adding this model as a part of DWOC. If this model is appropriate, kindly assign it to me. Thank you.

**Comment by akshitagupta15june** [comment]
great
assigning you
