### ISSUE TITLE
RingNet

### ISSUE THREAD

**Issue by infiniteoverflow** [akshitagupta15june/Face-X#167]
**Is your feature request related to a problem? Please describe.**
This feature is related to 3D Face Reconstuction

**Describe the solution you'd like**
I would like to implement the RingNet model that regresses 3D Face Shape and Expression from an Image without 3D Supervision.

**Approach to be followed (optional)**
The dataset and the pretrained RingNet weights can be downloaded from their website: https://ringnet.is.tue.mpg.de/

**Comment by infiniteoverflow** [comment]
@akshitagupta15june I am really interested in adding this model to the Face Reconstruction directory. This model has been of great help to me while studying about Face Reconstruction as this retrieves the face shape without using 3D Supervision.

Kindly let me know your views on the same. Thank you !!

**Comment by akshitagupta15june** [comment]
Great @infiniteoverflow i am assigning you.
Can you also make a main readme of face-reconstruction folder
Like the comparison analysis of all the operations of facial reconstruction

**Comment by infiniteoverflow** [comment]
Sure sure , but i guess its already assigned to someone else in issue #159 ?
