### ISSUE TITLE
Bug report: Face detection in Python using OpenCV

### ISSUE THREAD

**Issue by mehabhalodiya** [akshitagupta15june/Face-X#171]
**Describe the bug**
Face detection is a computer vision technology that helps to locate/visualize human faces in digital images. This technique is a specific use case of object detection technology that deals with detecting instances of semantic objects of a certain class (such as humans, buildings or cars) in digital images and videos. With the advent of technology, face detection has gained a lot of importance especially in fields like photography, security, and marketing.

https://github.com/akshitagupta15june/Face-X/tree/master/Face-Detection/Face-Detection-using-OpenCV
The above directory doesn't have proper explanation,

**To Reproduce**
I will create a directory containing:
1. A proper README file
2. Jupyter Notebook
3. Images as arrays and what's needed

**Additional details**
Objective: The idea is to introduce people to the concept of object detection in Python using the OpenCV library and how it can be utilized to perform tasks like Facial detection.

**Comment by akshitagupta15june** [comment]
Gram!
Assigning to u
