### ISSUE TITLE
learn.md not found

### ISSUE THREAD

**Issue by nagamukesh** [akshitagupta15june/Face-X#1766]
**Is your documentation request related to a problem? Please describe.**
I can make a learn.md file discussing the project explaining all the features and related technologies and screenshots according to gssoc 2024
please assign this issue to me under gssoc 2024

**Describe the documentation you want to improved**
I would like to add a learn.md file suggested by gssoc 2024 and I will try to describe all the projects/subsections in this repo concisely with some relevant information

**Comment by akshitagupta15june** [comment]
hey its not required.
