### ISSUE TITLE
YOLO could be a great alternative for Facial Detection instead of using CNN as CNN is quite slow compared to YOLO.

### ISSUE THREAD

**Issue by utsabsamadder** [akshitagupta15june/Face-X#1767]
**Is your feature request related to a problem? Please describe.**
YOLOv7 or v8(You Only Look Once) Model is quite new and could be used on the project.

I have already worked with YOLO V8 and i am sure I could make an improvement in this project with YOLO.

**Comment by YASH-YADAV-dynamo** [comment]
hey @utsabsamadder  i have done this work previously, so i would love to work on this issue  too under GSSOC'24.
Please assign me this issue.
my previous work reference:
https://github.com/YASH-YADAV-dynamo/Real_time_people_counting (in this i have used yolo v8, with coco dataset)

**Comment by akshitagupta15june** [comment]
Go for it!!
