### ISSUE TITLE
deep fake detection

### ISSUE THREAD

**Issue by Pranshu-jais** [akshitagupta15june/Face-X#1769]
**Is your feature request related to a problem? Please describe.**
title: Build a deepfake detection model 

**Describe the solution you'd like**
Solution : 
            1. Preprocessing of  dataset
            2. Build Image Loading Function
            3. Apply Image Augmentation on Images and Label
            4.  Build & train the  deep learning model
            5.  Test and  perform real time detection

*

**Comment by Divyanshi-2211** [comment]
Please assign this issue to me

**Comment by Pranshu-jais** [comment]
I request you  to assign me this issue with the gssoc label and the appropriate level (1/2/3). i have a good experience computer vision task and  to develop ml models .  i have worked on similar types of problems in my college projects

**Comment by vidurAgg22** [comment]
I request you to assign this issue to me I have already worked on this project with many different models like CNN, KNN , SVM and would like to resolve this issue.
github: https://github.com/vidurAgg22

**Comment by akshitagupta15june** [comment]
someone is working on this
