### ISSUE TITLE
Feature request: Introducing Deep Fake addition to public faces

### ISSUE THREAD

**Issue by Soubeer** [akshitagupta15june/Face-X#1772]
This can be great addition to either mimic celebrities or public figures as a meme or for explanatory purposes by users. This task can apply a face of a chosen personnel over another with the positions of the nose, mouth, eyes, etc. 

Using various clustering methods and ML algorithms, I can make a model which can accurately do the trick. It will be fast and representative as terms of work and not just a picture slapped on the human.

There is currently no alternative that is to be followed in this technique.

This task can also be used by people who want to test their project of Deepfake Detection to analyze how much their model  is performing in terms of accuracy to current world techniques.

Hope I make it to your sight.

Thanks...

**Comment by Sitevity** [comment]
I Want to Work on This Feature Request
thank You

**Comment by Soubeer** [comment]
@akshitagupta15june is this task assigned to me? I am not sure ,it doesn't show assignees

**Comment by akshitagupta15june** [comment]
Go for it!!

**Comment by Sitevity** [comment]
Hi, I am Working on this Issue, let it Reopen.
________________________________
