### ISSUE TITLE
Smart Select and OCR text Extraction 

### ISSUE THREAD

**Issue by litesh1123** [akshitagupta15june/Face-X#1774]
**Is your feature request related to a problem? Please describe.**
This is a genuine problem , many times while storing some important info that comes on screen user either manually note it out ,take a screenshot for manual noting down later , but with smart select feature user can extract text present in screen by selecting portion.

**Describe the solution you'd like**
user has to follow 3 steps
> Take a screenshot of the portion you want
>Give screenshot as input 
>OCR operations take place over screenshot and text is extracted

**Describe alternatives you've considered**
Alternate solution for future use , i am planning user will come use smart select , select portion he want , and text would be extracted there would no need to take ss , and give input follow this process (future solution) 

**Approach to be followed (optional)**
>user will take screenshot
>give path of screenshot , OCR operation takes place over image and text etracted will be stored
>OCR software  used will be Tesseract

**Additional context**
![smart select](https://github.com/akshitagupta15june/Face-X/assets/139573484/ac4125a7-c4ac-4945-aad1-7ae2948c14a1)

**Comment by INEcodes** [comment]
Want to work on this for GSSOC'24.

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by akshitagupta15june** [comment]
Hey its not related to frontal face operation.
