### ISSUE TITLE
Smile Percentage Detection

### ISSUE THREAD

**Issue by mehabhalodiya** [akshitagupta15june/Face-X#178]
**Related to: Smile detection using OpenCV**

I would like to add this in below directory - 
https://github.com/akshitagupta15june/Face-X/tree/master/Face-Emotions-Recognition

**Describe the solution you'd like**
This code will use the detectMultiScale method of the face classifier to first find faces in the frame. Once those are found, within each "region of interest", we look for smiles using the smile detector.

**Approach to be followed (optional)**
I will add a Jupyter notebook for clear and concise code with step-wise explanation.

**Comment by mehabhalodiya** [comment]
@akshitagupta15june Please assign me this under JWoC.
I would like to work on this.

**Comment by akshitagupta15june** [comment]
Hi @mehabhalodiya can you add a more feature in this by adding smiling percentage like how much percent smile or laugh is there.
It will be a great enhancement Because emotions Recognition is already added in repo.

**Comment by gopichandpuli9** [comment]
Can you assign this to me as a part of CrossWoC?

**Comment by akshitagupta15june** [comment]
Hi @gopichandpuli9 this is already assigned to @mehabhalodiya
