### ISSUE TITLE
Deep Face Detection with Caffe Implementation

### ISSUE THREAD

**Issue by smriti1313** [akshitagupta15june/Face-X#179]
**Is your feature request related to a problem? Please describe.**
Deep Face Detection with Caffe Implementation

**Describe the solution you'd like**
Face Detection can be done using various methods and algorithms. Once such feature is provided by [Caffe](http://caffe.berkeleyvision.org/). Hence, the folder will contains models and tests for facial Detection using caffe.

**Comment by akshitagupta15june** [comment]
Hi @smriti1313 assigning you.

**Comment by smriti1313** [comment]
Hi, I am a participant under DWoC.

**Comment by akshitagupta15june** [comment]
ok i am sorry for that
