### ISSUE TITLE
Addition of Face Recognition Library with many supported algorithms at a place

### ISSUE THREAD

**Issue by Raghucharan16** [akshitagupta15june/Face-X#1793]
**Is your feature request related to a problem? Please describe.**
DeepFace is advanced face recognition library and can be used for face detection, face recognition and Face Attribute Activity {Age, Race, Gender and Emotion}

**Describe the solution you'd like**
This library wraps up several state of art algorithms like VGG-Face, FaceNet, GhostFaceNet, DeepFace, SFace etc for recognition tasks , for face detection there are several backend_detectors like mcnnet, opencv, yolo, retinaface

**Describe alternatives you've considered**
As this Library supports state of art algorithms at one place, one can use thier own algorithm which fits thier usecase by trying all of the algorithms. And the cool thing is library gets updatedly regularly and new state of art algorithms will get updated in the library as above algorithms mentioned are limitedly trained on LFW dataset but datasets like:
 [MS1MV2](https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_#ms1m-arcface-85k-ids58m-images-57) (87k IDs, 5.8M images)
[MS1MV3](https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_#ms1m-retinaface) (93k IDs, 5.2M images)
[Glint360K](https://github.com/deepinsight/insightface/tree/master/recognition/partial_fc#4-download) (360k IDs, 17.1M images)
[WebFace42M](https://github.com/deepinsight/insightface/blob/master/recognition/arcface_torch/docs/prepare_webface42m.md) (2M IDs, 42.5M images) and are models in onnxformat which performs better on south asain and east asain faces. 

**Approach to be followed (optional)**
The process is pretty straight forward. you can just install the deepface library asit is availlable as pypi package.

**Additional context**
I'm not author of this library but i keep exploring libraries like this. The original repo is [here](https://github.com/serengil/deepface) and is regularly manitained. give a star if it helps anyone.

**Comment by aryanchauh** [comment]
Can you assign me this issue @akshitagupta15june

**Comment by aryanchauh** [comment]
Can you assign me this issue @akshitagupta15june

**Comment by akshitagupta15june** [comment]
hey most of the algorithms have been implemented, try to create issues with single algo that you want to add after checking the folders.

**Comment by Raghucharan16** [comment]
@akshitagupta15june Ok I see I checked the folders and recognition algorithms, and I came to know that face512 algorithm and deepface isn't there in the repo and I want to put facenet512 algorithm using deepface library so open this and assign me
