### ISSUE TITLE
GSSoC'24: Animal Equivalent of the Human Face

### ISSUE THREAD

**Issue by SAM-DEV007** [akshitagupta15june/Face-X#1816]
**Is your feature request related to a problem? Please describe.**
No. It is just a fun project.

**Describe the solution you'd like**
I would like to add a face detection algorithm which would detect a human face and tell the animal equivalent of the face detected, i.e., which animal the human face converges to. I would like to add the project under `Awesome-face-operations` folder with the name `HumanToAnimal-Detection`.

**Approach to be followed (optional)**
- OpenCV for UI interface.
- Detection of face from OpenCV.
- A pretrained VGG16 model which is then fine tuned for animal detection with a dataset of 15 different animals using Tensorflow and Keras.
- Cut the frame of the face from the detected face frame and send to the VGG model for animal detection.
- Displaying the result on the frame just above the face in the form of text.

Please assign me the issue under GSSoC'24.

**Comment by akshitagupta15june** [comment]
not required for this repository
