### ISSUE TITLE
Lung Cancer Detection:

### ISSUE THREAD

**Issue by Anshika14528** [akshitagupta15june/Face-X#1817]
Detection of Lung cancer  using  strategically designed convolutional layers, max pooling layers ,dense Layer and fully connected layers in Deep Learning.

I agree to follow this project's Code of Conduct
I'm a GSSoC'24 contributor
I want to work on this issue

**Comment by Tanishka023** [comment]
Hey @akshitagupta15june  Please assign this issue to me under SSOC'24, I really want to work on this.

**Comment by Shouryabhardwajj** [comment]
I am interested in this issue. Please assign me this

**Comment by akshitagupta15june** [comment]
its not related to face
