### ISSUE TITLE
Readme improvement for Cartoonify Image folder

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#182]
https://github.com/akshitagupta15june/Face-X/tree/master/Cartoonify%20Image

Include documentation required.

**Comment by Rukmini-Meda** [comment]
Hey,

Can I take this up as part of cross winter of code?

**Comment by akshitagupta15june** [comment]
Yes Ofcourse

**Comment by Sloth-Panda** [comment]
@akshitagupta15june can I take up this issue as part of dwoc and swoc?

**Comment by akshitagupta15june** [comment]
I think @Rukmini-Meda is working in it

**Comment by Rukmini-Meda** [comment]
Hello, Sorry I hadn't updated my status. I have been busy with my exams lately. I will unassign myself so that @Sloth-Panda can take this up.

**Comment by Sloth-Panda** [comment]
@akshitagupta15june  Do i just need to add these images ? I mean just one image?
