### ISSUE TITLE
Feature request : Multi-Modal Face Recognition System

### ISSUE THREAD

**Issue by UTSAVS26** [akshitagupta15june/Face-X#1822]
**Is your feature request related to a problem? Please describe.**  
The problem revolves around the need for a reliable face recognition system capable of overcoming challenges such as variations in lighting conditions, facial expressions, and angles, as well as similarities between different individuals' facial features. Existing face recognition approaches may not adequately address these challenges.

**Describe the solution you'd like**  
The desired solution is to develop a face recognition system utilizing various pre-trained models such as `Xception`, `ResNet50`, and `VGG16`. These models will undergo modifications using data augmentation techniques to enhance their accuracy under diverse conditions. Evaluation of each model's performance will be conducted using metrics like accuracy scores, loss, and confusion matrices to determine the most suitable model for the task.

**Describe alternatives you've considered**  
Considered alternatives include exploring different network architectures, employing alternative data augmentation techniques, and modifying existing models to improve the face recognition system's accuracy. Additionally, considering alternative datasets and exploring modifications to existing models are also viable options.

**Approach to be followed (optional)**  
The approach involves:
1. Utilizing multiple pre-trained models for face recognition.
2. Applying data augmentation techniques to enhance model accuracy.
3. Comparing model performance using various evaluation metrics.
4. Conducting `Exploratory Data Analysis (EDA)` to understand dataset characteristics.
5. Documenting the work performed comprehensively using a `README` file.

**Additional context**  
No additional context provided.

----------------------------------------------------------------------------------------------------------------------------------------
Full Name: Utsav Singhal
GitHub Profile Link: https://github.com/UTSAVS26
Participant ID (If not, then put NA): Contributor
What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.): SSOC

**Comment by akshitagupta15june** [comment]
Go for it! and add your implementation inside face recognition folder
