### ISSUE TITLE
Readme for face detection folder

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#183]
https://github.com/akshitagupta15june/Face-X/tree/master/Face-Detection

Add a proper readme with  the details from installation to execution

**Comment by Albert-Jokelin** [comment]
Hey, Can I work on this?

**Comment by akshitagupta15june** [comment]
yes you can!
are you a dwoc participant?

**Comment by akshitagupta15june** [comment]
@Albert-Jokelin are you a dwoc participant?

**Comment by mehabhalodiya** [comment]
Can I work on this @akshitagupta15june ?

**Comment by akshitagupta15june** [comment]
yes @mehabhalodiya
