### ISSUE TITLE
Develop a model to detect whether the person smiling or not

### ISSUE THREAD

**Issue by UppuluriKalyani** [akshitagupta15june/Face-X#1840]
Develop a model to detect whether the person smiling or not

**Comment by UppuluriKalyani** [comment]
@akshitagupta15june mam, can you please assign this issue to me.

**Comment by gaurimadan** [comment]
I am a SSOC contributor, @akshitagupta15june ma'am I have worked with opencv and mediapipe. I would like to contribute on this issue. Kindly assign me.

**Comment by Garvanand** [comment]
HI, @akshitagupta15june I have developed the real-time smile detection model made using OpenCV, Kindly assign the issue to me under GSSoC'24
