### ISSUE TITLE
Facial emotion recognition using deep learning

### ISSUE THREAD

**Issue by smriti1313** [akshitagupta15june/Face-X#188]
# Description:

Facial emotion recognition using deep learning 

# Dependencies:

Python 3, OpenCV, Tensorflow

let me know if there's a chance to work on it.
Thank you

**Comment by gopichandpuli9** [comment]
I would like to work on this.

**Comment by akshitagupta15june** [comment]
are u a dwoc participant?

**Comment by gopichandpuli9** [comment]
I'm a participant of Cross WoC

**Comment by akshitagupta15june** [comment]
assigning you.

**Comment by smriti1313** [comment]
Hi, @akshitagupta15june  

I opened this issue hoping that you could assign this to me. I request you to assign this to me.
Thank you

**Comment by akshitagupta15june** [comment]
I am sorry @gopichandpuli9 this issue will be assigned to @smriti1313 as she opened it.
You can search for new issues and let me know.

**Comment by akshitagupta15june** [comment]
@smriti1313 what label should i add swoc or dwoc?

**Comment by smriti1313** [comment]
First of all thank you so much for helping out everytime. I am sorry for being a trouble :). 

I am dwoc participant. 
Thank you

**Comment by akshitagupta15june** [comment]
ok great!

**Comment by gopichandpuli9** [comment]
But you first assigned it to me.
I started doing too
