### ISSUE TITLE
CAN WE MAKE IT TO DETECT MULTIPLE FACES?

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#2]

**Comment by Palaash05** [comment]
I would like to work on this project. I think I can solve this issue. I request you to please assign it to me.

**Comment by akshitagupta15june** [comment]
Ok

**Comment by Palaash05** [comment]
@akshitagupta15june  can I add some totally other code? I mean I have used a different library and it makes face detection really easy. I'll try to do it in real-time.

**Comment by akshitagupta15june** [comment]
Join Discord channel for discussion.
discord.gg/f9jftkcw

**Comment by ritikamishra01** [comment]
can i get assigned for this issue @akshitagupta15june ?

**Comment by akshitagupta15june** [comment]
Yes ofcourse

**Comment by akshitagupta15june** [comment]
Join discord too for any queries
