### ISSUE TITLE
Real-Time Liveness Based Face Recognition System

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#200]
use one of the modern ways of face recognition with a spoofing detection (eye blink-based) algorithm to show whether the user is drowsy or not.

**Comment by smriti1313** [comment]
Hi, I would like to do this under DWoC. I wanted to ask : the project should be able to recognize if the face is real or fake???

**Comment by smriti1313** [comment]
Hi, I would like to do this under DWoC. I wanted to ask : the project should be able to recognize if the face is real or fake???

**Comment by akshitagupta15june** [comment]
it can be a static photo or also in realtime
