### ISSUE TITLE
Landmark Detection and 3D Face Reconstruction for Caricature using a Nonlinear Parametric Model

### ISSUE THREAD

**Issue by infiniteoverflow** [akshitagupta15june/Face-X#204]
**Is your feature request related to a problem? Please describe.**
This adds a new model to the Face Reconstruction Directory

**Describe the solution you'd like**
Caricature is an artistic abstraction of the human face by distorting or exaggerating certain facial features, while still retains a likeness with the given face. Due to the large diversity of geometric and texture variations, automatic landmark detection and 3D face reconstruction for caricature is a challenging problem and has rarely been studied before.
This code develops model for the research paper : https://arxiv.org/abs/2004.09190

**Comment by akshitagupta15june** [comment]
assigned!
