### ISSUE TITLE
Installation steps have code block and inline code

### ISSUE THREAD

**Issue by eddiejaoude** [akshitagupta15june/Face-X#210]
https://github.com/akshitagupta15june/Face-X#installation-

### Before

<img width="764" alt="Screenshot 2021-02-19 at 18 38 52" src="https://user-images.githubusercontent.com/624760/108547076-ecbdc580-72e1-11eb-9799-6ce23485b895.png">

### After

<img width="1130" alt="Screenshot 2021-02-19 at 18 39 54" src="https://user-images.githubusercontent.com/624760/108547085-efb8b600-72e1-11eb-864b-13a42e8380ac.png">

**Comment by akshitagupta15june** [comment]
thanks for your contribution @eddiejaoude  by improving this project!
