### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by smriti1313** [akshitagupta15june/Face-X#219]
**Is your feature request related to a problem? Please describe.**
Blur face after recognizing it. 

**Describe the solution you'd like**
Blurring the face using opencv and python. We have seen how images are blurred in order to maintain the security or appropriateness. So adding a program that could blur the face.

**Additional context**
Like this:
![IMG_20210222_020623](https://user-images.githubusercontent.com/52624997/108637973-0a8e5480-74b3-11eb-96a4-e8b08ce349a0.jpg)

**Comment by simanfathima** [comment]
Can I work on this issue for SWOC?

**Comment by akshitagupta15june** [comment]
Hi i said background blurring is acceptable
Not the face blurring

**Comment by akshitagupta15june** [comment]
Please check your portrait mode in phone camera. @smriti1313

**Comment by akshitagupta15june** [comment]
I will create a new issue

**Comment by akshitagupta15june** [comment]
Ji
