### ISSUE TITLE
Correction of grammatical errors and sentence rephrasing in README.md

### ISSUE THREAD

**Issue by anirudhsai20** [akshitagupta15june/Face-X#221]
**Is your feature request related to a problem? Please describe.**
The description in the README.md has a lot of gramatical errors and  explanation can be made more clear. 

**Describe the solution you'd like**
The explanation can be made more clear and better by rephrasing them and by correcting the gramatical errors. 

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Comment by anirudhsai20** [comment]
Hi @akshitagupta15june . Can I please correct this issue under SWOC or DWOC?

**Comment by akshitagupta15june** [comment]
Yes Ofcourse! @anirudhsai20
