### ISSUE TITLE
Background Blurring across the face

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#222]
Keep a face in the focus and blur the background like we see in portrait modes.

**Comment by smriti1313** [comment]
Hi, i would like to work on this.

**Comment by smriti1313** [comment]
Hi, @akshitagupta15june since today is the last day of DWoC, so could you assign me this as early as possible? thank you

**Comment by simanfathima** [comment]
Hi, can I work on this issue?

**Comment by akshitagupta15june** [comment]
Ok @smriti1313
