### ISSUE TITLE
Face Recognition Using Inception V3 model.

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#229]

**Comment by koushik2001** [comment]
Can I work on this issue

**Comment by akshitagupta15june** [comment]
yes are u gssoc participant?

**Comment by koushik2001** [comment]
Yes

**Comment by akshitagupta15june** [comment]
OK @koushik2001

**Comment by abhishek-iiit** [comment]
can, i too work on the issue @akshitagupta15june ?
If so,can you please assign me this issue...

**Comment by akshitagupta15june** [comment]
No only one can be assigned at a time

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.
