### ISSUE TITLE
Create Contributors Guideline

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#232]
Objective

Create Contributors Guideline to help new Contributors get started with this Project.
Features

 1) Add a CONTRIBUTING.md to allow new users to get started with knowing how to contribute.
 2) Add Screenshots wherever possible.
 3) Add the basic information about creating Issues, Pull Requests, and Branching.
 4) Mention tutorials related to Git and Github to help them better understand.

**Comment by smriti1313** [comment]
Hi, I would like to do this under DWoC

**Comment by mehabhalodiya** [comment]
Hi, I would like to work on this under GSSoC'21.

**Comment by akshitagupta15june** [comment]
Hi i think coding period will start from 1 st

**Comment by mehabhalodiya** [comment]
> Hi i think coding period will start from 1 st

Yes, GSSOC'21 KickStarts on 1st March.

**Comment by akshitagupta15june** [comment]
Ok assigning you

**Comment by akshitagupta15june** [comment]
hi i have completed the guidelines because some picture required my repo.
