### ISSUE TITLE
Google colab module can be removed from cartoonify_face_image

### ISSUE THREAD

**Issue by sudipg4112001** [akshitagupta15june/Face-X#236]
The code can be made more simple and detailed removing `from google.colab.patches import cv2_show` and using other alternatives in place of it. The, code can also be more user interactive.
I would like to work under GSSOC'21.

**Comment by akshitagupta15june** [comment]
are you a gssoc participant?

**Comment by sudipg4112001** [comment]
> are you a gssoc participant?

Yes

**Comment by akshitagupta15june** [comment]
ok @sudipg4112001
