### ISSUE TITLE
Readme Improvement in face-x readme

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#237]
[Readme](https://github.com/akshitagupta15june/Face-X/blob/master/README.md)

**Comment by mehabhalodiya** [comment]
I would like to work on this under GSSoC'21.

**Comment by akshitagupta15june** [comment]
ok

**Comment by mehabhalodiya** [comment]
Can you please let me know that how many days I am having to submit a PR regarding this as coding period starts from 8th March according to GSSoC'21 Timeline ?

Kindly check it out and then let me know.

**Comment by akshitagupta15june** [comment]
You can submit after 8

**Comment by srimontidutta** [comment]
Can I please work on this documentation? (GSSoC 21)

**Comment by akshitagupta15june** [comment]
@mehabhalodiya is already assigned

**Comment by mehabhalodiya** [comment]
@akshitagupta15june  Yes, I am working.
