### ISSUE TITLE
Associating link of crosswoc website to its banner

### ISSUE THREAD

**Issue by kmryashasvi** [akshitagupta15june/Face-X#239]
**Is your documentation request related to a problem? Please describe.**
No.

**Describe the documentation you want to improved**
I want to improve readme file of this repository

**Additional context**
I will associate link of the crosswoc website to its banner such that, if someone clicks the banner on readme file, it will redirect them to the website of crosswoc.

**Comment by akshitagupta15june** [comment]
can you do some more improvements in the readme if you can while I am assigning you?

**Comment by akshitagupta15june** [comment]
are you a gssoc participant?

**Comment by kmryashasvi** [comment]
> are you a gssoc participant?

no

**Comment by kmryashasvi** [comment]
I have not applied, I am going to apply soon for gssoc

**Comment by akshitagupta15june** [comment]
ok adding crosswoc label

**Comment by kmryashasvi** [comment]
> can you do some more improvements in the readme if you can while I am assigning you?

Can you specify what type of more changes you want?

**Comment by akshitagupta15june** [comment]
changes like contributors picture is not working safari in macos

**Comment by kmryashasvi** [comment]
> changes like contributors picture is not working safari in macos

 You have to turn off prevent cross site tracking under privacy in Safari. 
In my opinion, this problem is not with the code.
You should try embedding the pictures from google drive, but it will be tedious, won't it????????

**Comment by akshitagupta15june** [comment]
yes it can be so whatever you think you can make improvements.

**Comment by akshitagupta15june** [comment]
let me know whatever you have made.

**Comment by kmryashasvi** [comment]
What i can do is to add link of the events to all banners present in your readme file,

**Comment by akshitagupta15june** [comment]
yes, you can then.

**Comment by kmryashasvi** [comment]
I'll have no problem adding new things to the readme,
you can close this issue now if you don't want to add the following features to the readme file
1. Adding a paragraph on the importance of facial recognition.
2. Adding a paragraph on the importance of your project on the betterment of society.

(I'll need extra points from you about your project if you want to implement the 2nd point mentioned above.)

**Comment by akshitagupta15june** [comment]
no its not required till now i will merge your or after 8.

**Comment by akshitagupta15june** [comment]
when the coding period starts

**Comment by akshitagupta15june** [comment]
no its not required right now i merge your pr.
