### ISSUE TITLE
Add face swapping feature

### ISSUE THREAD

**Issue by sudipg4112001** [akshitagupta15june/Face-X#241]
I would like to add a project for face swapping, under GSSOC'21

**Comment by akshitagupta15june** [comment]
great assigning you

**Comment by akshitagupta15june** [comment]
try to create a new folder in the repo for that with this convention "Face-Swapping"

**Comment by sudipg4112001** [comment]
Yes I will, while doing the pull request

**Comment by sudipg4112001** [comment]
Previously I have made a PR for issue #236 , should I make a separate PR for this issue after that PR is merged or can I upload the files before merging ?
To be more precise, if a single PR contains commits from 2 issues, will there be any problem ?

**Comment by akshitagupta15june** [comment]
As you are implementing a different feature then or should be different

**Comment by sudipg4112001** [comment]
Then I have to wait for my previous PR to be merged ?

**Comment by akshitagupta15june** [comment]
No you can create prs but all will be merged after 8

**Comment by sudipg4112001** [comment]
Actually, the problem is I have done a PR for the issue #236 which is not merged till now. Now, if I make changes for this issues, it will come under the same PR.

**Comment by akshitagupta15june** [comment]
You can change the branches if you want

**Comment by akshitagupta15june** [comment]
Ok let it be

**Comment by akshitagupta15june** [comment]
Mention both issues in the same pr.
I will see to it

**Comment by sudipg4112001** [comment]
Okay..!! Thank You
