### ISSUE TITLE
I want to add comments to all the files

### ISSUE THREAD

**Issue by kmryashasvi** [akshitagupta15june/Face-X#242]
Comments are very necessary to any of the source file,
Moreover, comments are considered as an important element in coding tests of many companies,
Hence, I want to add comments to all the files present in the repo irrespective of the language of the files

**Comment by akshitagupta15june** [comment]
hey changing to any of code file is not needed in this repo

**Comment by akshitagupta15june** [comment]
you can work on the different opened issues

**Comment by kmryashasvi** [comment]
kya batayen, 
sab bahut hard issue hai
phir bhi dekhte hain
thank you
