### ISSUE TITLE
Cartoonifying image using openCV

### ISSUE THREAD

**Issue by Jaideep07** [akshitagupta15june/Face-X#248]
I would like to contribute to this repo as a part of GSSOC21. Can you please assign me this issue

**Comment by akshitagupta15june** [comment]
great @Jaideep07 assigning you

**Comment by pallavidhere23** [comment]
Hello,I am a participant @GSSOC'2021 ,can u please assign me this issue.

**Comment by get-satyam** [comment]
Hello, I would love to work on this issue and contribute to this repo as a GSSoC '21 Participant. Can you please assign me this issue?

**Comment by akshitagupta15june** [comment]
This issue is already assigned.

**Comment by akshitagupta15june** [comment]
To @Jaideep07

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by akshitagupta15june** [comment]
yes you can work on this

**Comment by Hamza3226** [comment]
> yes you can work on this

Ok ma'am
