### ISSUE TITLE
readme Improvement for Recognition_using_mtcnn

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#251]
https://github.com/akshitagupta15june/Face-X/tree/master/Recognition-Algorithms/Recognition_using_mtcnn

**Comment by avishkar2001** [comment]
Can I work on this issue as I am an active participant in GSSOC21?

**Comment by Sloth-Panda** [comment]
would like to work on this @akshitagupta15june

**Comment by akshitagupta15june** [comment]
In fcfs
