### ISSUE TITLE
readme  Improvement for virtual makeover folder

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#252]
https://github.com/akshitagupta15june/Face-X/tree/master/Virtual_makeover

**Comment by avishkar2001** [comment]
Can I work on this issue as I am an active participant in GSSOC21?

**Comment by Sloth-Panda** [comment]
would like to work on this

**Comment by akshitagupta15june** [comment]
Assigning in fcfs to @ManviGoel26
