### ISSUE TITLE
Readme improvement for snap chat folder

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#254]
https://github.com/akshitagupta15june/Face-X/tree/master/Snapchat_Filters

**Comment by anandxkumar** [comment]
Hi, I'm a  GSSOC'21  aspirant I would like to improve the Readme content of the Snap Chat Folder, can I be assigned the same ?

**Comment by akshitagupta15june** [comment]
sure assigning you @anandxkumar
