### ISSUE TITLE
Add missing algorithms comparison in readme file

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#255]
Some more new algos have been algorithms add them in the table along with comparison.
https://github.com/akshitagupta15june/Face-X/tree/master/Recognition-Algorithms

**Comment by PankajGit2711** [comment]
Hi Akshita! This is in reference to your above issue and I decided to look over it. Could you please address a thing that whether your intention was to write "Mission" or "Missing" in the Issue headline as I see in the readme file that there's no algorithm named Mission. So please clarify that and if you mistakenly wrote it then could you please correct it. Also with your permission can I take this task as a part of GSSOC'21 contributions?

**Comment by akshitagupta15june** [comment]
yes you can take it.
It was missing.

**Comment by PankajGit2711** [comment]
Okay Thank You!

**Comment by PankajGit2711** [comment]
Should I categorize EfficientNet B0, B1, B2 Separately or is the single declaration for EfficientNet is enough?

**Comment by PankajGit2711** [comment]
Added a PR Akshita! Please check.
