### ISSUE TITLE
Recognition using DWT algorithm

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#256]
Implement Recognition using DWT DISCRETE WAVELET TRANSFORM

**Comment by carrycooldude** [comment]
Hey @akshitagupta15june I am interested to work on this issue and if possible can you share some resources on that front

**Comment by Pavithra2206** [comment]
Hey @akshitagupta15june i want to work on this issue as a GSSOC'21 participant. Can you assign me ?

**Comment by Pavithra2206** [comment]
hey @akshitagupta15june can i use matlab to implement DWT transform or only python ?

**Comment by akshitagupta15june** [comment]
assigning in fcfs to @carrycooldude

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.
