### ISSUE TITLE
Readme improvement for recognition using IOT Implementation

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#257]
https://github.com/akshitagupta15june/Face-X/tree/master/Recognition-using-IOT

**Comment by harshsinha03** [comment]
@akshitagupta15june  would like to work on this please assign me this issue

**Comment by rajeshpanjiyar** [comment]
I also want to work on this. I request you to assign me too

**Comment by harshsinha03** [comment]
I have already completed my assigned task and i am already experienced in IOT so please assign this issue to me as i can complete the readme file  by today EOD @akshitagupta15june
