### ISSUE TITLE
Bug report: Contributors image in face-x Readme is not opening in Safari in MacOS

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#258]
Contributors image in face-x Readme is not opening in Safari in MacOS

Improvement needed in contributors image in face-x Readme.

**Comment by escher-m** [comment]
Hi @akshitagupta15june, 
I am using Safari on MacOS Big Sur and I am able to view the contributors' images. I am attaching screenshots here.
Could you please clarify 'contributors image' so I could work on this issue?
![Screenshot 2021-03-10 at 2 51 57 PM](https://user-images.githubusercontent.com/62093616/110606895-a9ec6080-81b0-11eb-866f-f830c9abc357.png)
![Screenshot 2021-03-10 at 2 52 19 PM](https://user-images.githubusercontent.com/62093616/110606906-ae187e00-81b0-11eb-866e-df286d5390ab.png)

**Comment by akshitagupta15june** [comment]
Yes i am assigning you

**Comment by akshitagupta15june** [comment]
In many Safari it is not visible
