### ISSUE TITLE
readme Improvement for caffe model implementation

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#260]
https://github.com/akshitagupta15june/Face-X/tree/master/Face-Detection/face%20detection%20using%20caffe

**Comment by rudrani05** [comment]
Hi @akshitagupta15june I'm gssoc'21 participant. Can you kindly explain me what and all improvement you need in readme for caffe model implementation. I would love to do this. Thank you!

**Comment by akshitagupta15june** [comment]
It's like you can add information about its output and some more information

**Comment by rudrani05** [comment]
Okay

**Comment by rudrani05** [comment]
I have sent a PR , pls verify and let me know if any changes are required.

**Comment by rudrani05** [comment]
His @akshitagupta15june I have sent a pr and this is my first pr , pls verify it and let me know if there any changes are required.
