### ISSUE TITLE
Face Mask Detection

### ISSUE THREAD

**Issue by sudipg4112001** [akshitagupta15june/Face-X#265]
I would like to add a project for face mask detection. Here, I would use dataset with sample images of human faces and then detect whether  they are wearing not

**Comment by akshitagupta15june** [comment]
Yes you can create a Forder named face-mask-detection
Then you can add your implementations.

**Comment by sudipg4112001** [comment]
> Yes you can create a Forder named face-mask-detection
> Then you can add your implementations.

Okay!!

**Comment by rk05-lenavo** [comment]
I'm participant from GSSOC'21. I want to work on this issue. Please assign me this.

**Comment by sudipg4112001** [comment]
> I'm participant from GSSOC'21. I want to work on this issue. Please assign me this.

Hey, I have already made a PR for this issue.. Try some other issue
