### ISSUE TITLE
Recogntion using EigenFaceRecogniser

### ISSUE THREAD

**Issue by ashwani-rathee** [akshitagupta15june/Face-X#27]
Doing the FaceRecognition using EigenFaceRecogniser iin OpenCV

**Comment by utkarsh0702** [comment]
Can I try it?

**Comment by ashwani-rathee** [comment]
Well,I want to do it,because I'm lagging behind in points...as nobody is willing to give up their own issue which they haven't submitted PRs in even 10 days.But If I go that way,It would be against the spirit of opensource....so from my side you can go ahead, @akshitagupta15june can only assign you,so there is that.

**Comment by utkarsh0702** [comment]
@ashwani-rathee Thank you for giving the opportunity. Truly speaking this would be my first issue to work on.

**Comment by akshitagupta15june** [comment]
@ashwani-rathee assigning it to u
