### ISSUE TITLE
attendance marking system using face recognition and OpenCV

### ISSUE THREAD

**Issue by harshsinha03** [akshitagupta15june/Face-X#271]
would like to propose an program in python that will train from a dataset using openCV and while using a webcam or any picture if the program recognises it the attendance will be marked in a .txt file.

as a participant for GSSOC'21 and would love to work on this 
please assign me this issue

[GSSOC'21] - LABEL

**Comment by akshitagupta15june** [comment]
@mayank8200 will help you in this

**Comment by SpecTEviL** [comment]
Hey @akshitagupta15june, I'm Vishal Patil and I would like to work on this issue under GSSoC'21. It'll be great if you assign this to me as well so that I can contribute to this along with @harshsinha03.
Thanks!

**Comment by akshitagupta15june** [comment]
hi if i will assign to two then there will be two pr and there can be conflict.

**Comment by SpecTEviL** [comment]
> hi if i will assign to two then there will be two pr and there can be conflict.

I and @harshsinha03 can work together dividing the work among ourselves if @harshsinha03 is fine with that. We will try to first merge our code and then make a single PR.
Thanks.

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.
