### ISSUE TITLE
Readme Improvement for Cartoonify Image folder

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#273]
https://github.com/akshitagupta15june/Face-X/tree/master/Cartoonify%20Image

**Comment by Jainish-shah** [comment]
I would like to work on the Readme file.
As a GSSoC participant, I would like to contribute.

**Comment by akshitagupta15june** [comment]
sure

**Comment by Sibasish-Padhy** [comment]
I would like to work on readme file as a gssoc participant can u also assign me with this task

**Comment by Jainish-shah** [comment]
Should I include the basic algorithm used in all the Cartoonify Technique in the readme
