### ISSUE TITLE
readme Improvement for cartoonification folder

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#274]
https://github.com/akshitagupta15june/Face-X/tree/master/Cartoonify%20Image/Cartoonify_face_image

**Comment by Ashishsingh619** [comment]
Hi, I'm a GSSoC`21 participant and want to contribute to this. I have good knowledge about Cartoonification and want to work on it, So can you please assign me this issue.
@akshitagupta15june
