### ISSUE TITLE
Readme Improvement for Face detection using dlib hog folder

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#275]
https://github.com/akshitagupta15june/Face-X/tree/master/Face-Detection/Face%20detection%20using%20dlib%20hog

**Comment by rajeshpanjiyar** [comment]
I want to work on this issue. I request you to assign me this.

**Comment by Sanika1999** [comment]
Can I work on this?

**Comment by akshitagupta15june** [comment]
Assigning to @Sanika1999

**Comment by Sanika1999** [comment]
Hi @akshitagupta15june  could you please mention what kind of changes need to be done in this readme

**Comment by akshitagupta15june** [comment]
@Sanika1999 improvements like how to run this , some more info about this implementation

**Comment by akshitagupta15june** [comment]
you can take help from another readme present in the repo

**Comment by Sanika1999** [comment]
Sure thanks
