### ISSUE TITLE
Readme Improvement for face-swapping folder

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#278]
https://github.com/akshitagupta15june/Face-X/tree/master/Face-Swapping

**Comment by sadaffateema** [comment]
I'd love to work on this issue, can you please assign this to me under GSSOC'21

**Comment by tarannum-perween** [comment]
I want to work on this issue. Can you please assign this to me under GSSOC'21

**Comment by SpecTEviL** [comment]
Hey @akshitagupta15june, I'm Vishal Patil and I would like to work on this issue under GSSoC'21. It'll be great if you assign this to me so that I can contribute to this.
Thanks!

**Comment by akshitagupta15june** [comment]
Assigning to @sadaffateema

**Comment by Sibasish-Padhy** [comment]
hey @akshitagupta15june ,I'm Sibasish Padhy and I would like to work on this issue under GSSoC'21.It'll be great if you assign this to me for contribution
