### ISSUE TITLE
Recognition using MTCNN

### ISSUE THREAD

**Issue by ashwani-rathee** [akshitagupta15june/Face-X#28]
Doing the face recognition using MTCNN

**Comment by ParthPathak27** [comment]
I would like to work on this issue

**Comment by ParthPathak27** [comment]
I would like to work on this issue.

**Comment by ashwani-rathee** [comment]
@ParthPathak27 already working on it mate

**Comment by ashwani-rathee** [comment]
MTCNN and FaceNet works for different parts of the same problem and can be used together to solve the problem of FaceRecognition,so closing #29
