### ISSUE TITLE
Readme Improvement for snapchat filter readme

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#280]
https://github.com/akshitagupta15june/Face-X/tree/master/Snapchat_Filters

add the details of all filter implemented along with enhancement

**Comment by A-kriti** [comment]
Hello Akshita mam, I would like to contribute to this issue as a GSSOC'21 participant. So could you please assign me this?

**Comment by SpecTEviL** [comment]
Hey @akshitagupta15june, I'm Vishal Patil and I would like to work on this issue under GSSoC'21. It'll be great if you assign this to me so that I can contribute to this.
Thanks!

**Comment by akshitagupta15june** [comment]
assigning to @A-kriti
