### ISSUE TITLE
Want to Add more optimized code in FaceDetection.py File

### ISSUE THREAD

**Issue by anubhav201241** [akshitagupta15june/Face-X#286]
**The bug**
In Face-Detection-Open-CV folder the second folder in that facedetection.py code is not completely optimized 
 **To Reproduce**
I want to work upon this and want to submit more optimized and suitable code 

Kindly Assigned this part to me :)
I can update the code in more optimized and more Featurable way 

@akshitagupta15june  and Kindly plz assign this task to me and label as this as GSSOC'21 
Thank you :)

**Comment by akshitagupta15june** [comment]
ok great u can work on it.

**Comment by anubhav201241** [comment]
ok Mam, Thank you for assigning me This Task :)

**Comment by jeelnathani** [comment]
hello, I am gssoc '21 participant. I would like contribute on nose detection. assign it to me :)
