### ISSUE TITLE
Face and Eye Detection

### ISSUE THREAD

**Issue by iaditichine** [akshitagupta15june/Face-X#288]
Along with face detection,eyes detection is crucial in many Human-Machine interface system. Face and eyes detection can be done using Haar Cascade classifier. High detection ratio can be obtained with these classifiers. An output of the same is attached below.
![eye detection](https://user-images.githubusercontent.com/58857630/110735371-aeb42180-824f-11eb-9614-a00a037e6b74.jpg)
![eye detection](https://user-images.githubusercontent.com/58857630/110735390-bc69a700-824f-11eb-9d0d-4838a6363508.jpg)

**Comment by iaditichine** [comment]
Sure. Should I start contributing? Like the code and stuff as it's open
source.

**Comment by iaditichine** [comment]
Hey @akshitagupta15june, i want to add this feature in this project.

**Comment by akshitagupta15june** [comment]
hi @iaditichine add your implementation here in this folder https://github.com/akshitagupta15june/Face-X/tree/master/Face-Detection by the naming convention face-eye-detection also create a good informative readme

**Comment by iaditichine** [comment]
Will do, thanks! Should I create a pr?
