### ISSUE TITLE
Recognition using FaceNet

### ISSUE THREAD

**Issue by ashwani-rathee** [akshitagupta15june/Face-X#29]
Doing the face recognition using FaceNet

**Comment by ashwani-rathee** [comment]
Hey @akshitagupta15june ,Can I work on this now??

**Comment by akshitagupta15june** [comment]
Yes @ashwani-rathee

**Comment by ashwani-rathee** [comment]
@akshitagupta15june  Do I need to collect my own data like before,or I can use other datasets??
Also Do I have to write scripts or can I write Jupyter Notebook??or both maybe

**Comment by akshitagupta15june** [comment]
Anything in which u are comfortable

**Comment by akshitagupta15june** [comment]
Make sure to make a proper readme file along with every pull request showing all procedure and output

**Comment by ashwani-rathee** [comment]
@akshitagupta15june it can be closed,I would be using both MTCNN and FaceNet for the same purpose

**Comment by akshitagupta15june** [comment]
ok @ashwani-rathee have you checked your points?

**Comment by ashwani-rathee** [comment]
Yeah I have!!They have already been updated,thank you
