### ISSUE TITLE
Face recognition using  ICA    (Independent    Component Analysis)

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#297]

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by Preeti2095** [comment]
I would like to work on this @akshitagupta15june. Can you assign it to me?

**Comment by akshitagupta15june** [comment]
assigning in fcfs to @Hamza3226

**Comment by Preeti2095** [comment]
Ok. No problem. All the best @Hamza3226.

**Comment by Hamza3226** [comment]
> Ok. No problem. All the best @Hamza3226.

Thank You

**Comment by akshitagupta15june** [comment]
are you still working on this issue?

**Comment by Hamza3226** [comment]
> are you still working on this issue?

No Ma'am.

**Comment by Vi1234sh12** [comment]
Hey @akshitagupta15june  , Can I work on Issue  Please let me know

**Comment by akshitagupta15june** [comment]
yes
