### ISSUE TITLE
Add details about ResNet50 in readme

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#301]
https://github.com/akshitagupta15june/Face-X/tree/master/Recognition-Algorithms/Recognition%20using%20ResNet50

**Comment by Sibasish-Padhy** [comment]
hi @akshitagupta15june i am a gssoc participant 2021 and I would like to contribute on this issue.Can u assign me with this task?

**Comment by rajeshpanjiyar** [comment]
I want to work on this. I request you to assign me this one.

**Comment by Nidhi-2000** [comment]
Hey I am Nidhi participant of gssoc '21. Kindly assign this issue to me

**Comment by akshitagupta15june** [comment]
assining to @Sibasish-Padhy
