### ISSUE TITLE
Add a readme for GUI of LBPH Algo

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#302]
https://github.com/akshitagupta15june/Face-X/tree/master/GUI_for_Face%20Recognistion_using_LBPH_algo

**Comment by rajeshpanjiyar** [comment]
Hi I am a participant in GSSOC'21. I want to work on this so I request you to assign me this.

**Comment by akshitagupta15june** [comment]
ok assigning you
