### ISSUE TITLE
Readme Improvement for SIFT ALGO

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#305]
https://github.com/akshitagupta15june/Face-X/tree/master/Recognition-Algorithms/Recognition%20using%20SIFT

ADD MORE INFORMATION ABOUT THIS ALGO AND THE WAY OF EXECUTING IT.

**Comment by utkarsh147-del** [comment]
Assign this to me

**Comment by utkarsh147-del** [comment]
Mam,I have update readme of Resnet50,so please merge pull request of that also

**Comment by akshitagupta15june** [comment]
Assigning to u

**Comment by utkarsh147-del** [comment]
Pull request is generated for this
