### ISSUE TITLE
In cartoonify_face_image folder in the cartoon-face_image.py file. I want to make it work for live video Processing through Webcam or laptop camera which is better than reading a single image and cartoonifying it.

### ISSUE THREAD

**Issue by Ashishsingh619** [akshitagupta15june/Face-X#319]
The cartoon-face_image.py  is working for only a single image for which the image needs to be saved first then put into the cv2.imread function. So I want to make it for making it work for live video processing through webcam or laptop camera as the user starts the camera he can see his live cartoonified video instead of a single frame in the earlier case.
 
So @akshitagupta15june ma'am please assign me this issue I would like to work on it.

**Comment by akshitagupta15june** [comment]
work on it but give the proper screenshot of working in the readme present.
