### ISSUE TITLE
Face Mask detector in PyTorch

### ISSUE THREAD

**Issue by arnab031** [akshitagupta15june/Face-X#321]
**Statement**
We will develop a Face Mask detector.

**Solution**
Using deep learning model we will try to approach it.

**Comment by arnab031** [comment]
As a GSSOC21 Participant , I would like to work on this issue. @akshitagupta15june

**Comment by akshitagupta15june** [comment]
@arnab031 please add your implementation inside this folder https://github.com/akshitagupta15june/Face-X/tree/master/Face-Mask-Detection by creating a name face-mask-detection-pytorch
