### ISSUE TITLE
Add github action to auto label issues

### ISSUE THREAD

**Issue by Aayush-hub** [akshitagupta15june/Face-X#322]
**Is your feature request related to a problem? Please describe.**
Add github action to auto label issues with gssoc21 label, if the contributor asks to work on the issue under GSSOC21.

**Comment by Aayush-hub** [comment]
@akshitagupta15june Can I look into it??

**Comment by akshitagupta15june** [comment]
hi @Aayush-hub github action are not allowed in this repo

**Comment by Aayush-hub** [comment]
@akshitagupta15june Sure, no problem mam . Looking forward for more contributions :)
