### ISSUE TITLE
Add a readme for face - mask - detection 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#328]
https://github.com/akshitagupta15june/Face-X/tree/master/Face-Mask-Detection

**Comment by AshuKV** [comment]
Hi I am a GSSOC'21 participant. I want to work on this issue under GSSoC'21. Can you please assign it to me?

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by akshitagupta15june** [comment]
assigning

**Comment by rajeshpanjiyar** [comment]
Can I be assigned to work on this? I am a participant in GSSoC'21

**Comment by AshuKV** [comment]
I want to work on this issue under GSSoC'21. Can you please assign it to me?

**Comment by akshitagupta15june** [comment]
@akshatvirmani are you still working on this?

**Comment by rajeshpanjiyar** [comment]
What is the deadline for level1 issue? I think it's over

**Comment by akshatvirmani** [comment]
Yes Ma'am, I am trying it but I am facing difficulties.
