### ISSUE TITLE
Readme improvement in face-mask-detection-pytorch

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#329]
https://github.com/akshitagupta15june/Face-X/tree/master/Face-Mask-Detection/face-mask-detection-pytorch

add some more information, and regarding how to run this.

**Comment by AshuKV** [comment]
Hi I am a GSSOC'21 participant. I want to work on this issue under GSSoC'21. Can you please assign it to me?

**Comment by rudrani05** [comment]
Hi @akshitagupta15june , if no one is assigned yet, can I update this readme file.

**Comment by subhanjan160901** [comment]
Hi @akshitagupta15june , can I get to work on this?

**Comment by akshitagupta15june** [comment]
assigning to @AshuKV
