### ISSUE TITLE
Bug report issue in Glasses on face filter

### ISSUE THREAD

**Issue by Komal-99** [akshitagupta15june/Face-X#330]
**Describe the bug**
1.No requirements file is made for downloading required python modules.
2.In Readme their should pip command to download modules also  it should be creative 
3.Video can be added for Filter working expectation 
4. In Images folder their can more images added for more good looking repo

**To Reproduce**
1. creating requirements.txt file
2. Updating Read me
3. updating Images
4. 
**Expected behavior**
Read me should have detailed information regarding the filter working.

**Actual behavior**
Code didn't run because of modules not found.

**Screenshots**
![image](https://user-images.githubusercontent.com/74819092/111036478-60687380-8445-11eb-9a92-eb890d65b664.png)

**Additional details**

**Comment by Komal-99** [comment]
I would like to work on this issue. Gssoc'21 participant

**Comment by akshitagupta15june** [comment]
Assigning you

**Comment by Preeti2095** [comment]
is this issue is resolved @Komal-99?

**Comment by Komal-99** [comment]
Will complete by today.

**Comment by Preeti2095** [comment]
Ok.

**Comment by akshitagupta15june** [comment]
are you still working on this issue?

**Comment by Komal-99** [comment]
Yes.. actually I am facing some requirements issue before running this issue. .as in  this filter no where mention regarding  modules needed. When I putted my issue on discord no one. Help me with error so I am still trying to fix it out

**Comment by Preeti2095** [comment]
Can you again put your issue or ping your problem in discord @Komal-99 ?

**Comment by Komal-99** [comment]
Okay

**Comment by Komal-99** [comment]
hi please assign it to me as I told you in discord channel know i have founded the solution of error  and will be making an PR for the changes

**Comment by akshitagupta15june** [comment]
Ok

**Comment by Komal-99** [comment]
Please as per my request  increase its level as added kore than just read me .

**Comment by akshitagupta15june** [comment]
Yes i have merged the pr with level 2 tag

**Comment by Komal-99** [comment]
Thank you
