### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by Preeti2095** [akshitagupta15june/Face-X#333]
**Is your documentation request related to a problem? Please describe.**
There is a spelling mistake in the last line in readme.md of recognition algorithm folder.
Mistake:- Cecognition

**Describe the documentation you want to improved**
Correction:- Recognition

![Screenshot_20210314_122746](https://user-images.githubusercontent.com/70755131/111060145-c6461100-84c0-11eb-8ac0-14acbe827531.JPG)

**Comment by akshitagupta15june** [comment]
assigned
