### ISSUE TITLE
Face Mask Detection using VGG16 architecture

### ISSUE THREAD

**Issue by hrithikppawar** [akshitagupta15june/Face-X#339]
I am a **GSSOC participant**. I would like to work on a **Face Mask Detection** project with **VGG16** architecture and I will be using **Tensorflow** for it. Assign this issue to me, so that I can start contributing.

**Comment by akshitagupta15june** [comment]
assigning

**Comment by ahmed-cyber** [comment]
I am a GSSOC participant. I would like to work on a Face Mask Detection project with VGG16 architecture . Assign this issue to me, so that I can start contributing.

**Comment by ahmed-cyber** [comment]
@akshitagupta15june

**Comment by AdityaNikhil** [comment]
@hrithikppawar Have you completed this project? If so, please save your model to integrate with [Face-X Library](https://github.com/akshitagupta15june/Face-X/projects/3). So that your model will be easy to implement with one line of code.

**Comment by ahmed-cyber** [comment]
Not yet but i want to work on it ,i'm gssoc participant

**Comment by akshitagupta15june** [comment]
Hi @ahmed-cyber i think someone else is working in this issie

**Comment by ahmed-cyber** [comment]
@AdityaNikhil  I guess that doesn't stop me from working on many issues has more than one contributor

**Comment by akshitagupta15june** [comment]
No every issue those are some selected issues like snapchat filter issue that can have more than one assognees

**Comment by hrithikppawar** [comment]
> @hrithikppawar Have you completed this project? If so, please save your model to integrate with [Face-X Library](https://github.com/akshitagupta15june/Face-X/issues/312). So that your model will be easy to implement with one line of code.

I saved the model but its size is more than 100MB that's why I am unable to push it to the repository.

**Comment by AdityaNikhil** [comment]
@hrithikppawar It's okay, save your model in drive and paste the link here. 
We can host the model from Google Drive.

**Comment by hrithikppawar** [comment]
@AdityaNikhil 
Here is the drive link to the saved model of Face Mask Detection.
[face_mask_detection_vgg16.h5](https://drive.google.com/file/d/1EaRBH2FN1HJSlK7Og9UtomfPnh9r8_-1/view?usp=sharing)

**Comment by AdityaNikhil** [comment]
@hrithikppawar Please make your link public.
