### ISSUE TITLE
Pencil Sketch

### ISSUE THREAD

**Issue by iaditichine** [akshitagupta15june/Face-X#342]
Hello,I am a GSSOC'21 participant and i would like to add a feature called Pencil Sketch which converts Facial image or any other input image to a Pencil Sketch. It is done using Opencv. Please assign this issue to me. @akshitagupta15june 
![output_sketch](https://user-images.githubusercontent.com/58857630/111116245-c19a5f00-858b-11eb-860c-2ab3586e4c1e.png)

**Comment by akshitagupta15june** [comment]
can you add this implementation in snap filter folder

**Comment by iaditichine** [comment]
Sure. I will implement it in snap filter folder.
