### ISSUE TITLE
Semantic Face Segmentation

### ISSUE THREAD

**Issue by nandinib1999** [akshitagupta15june/Face-X#350]
**Describe the solution you'd like**
I would like to implement a model for face segmentation. It will segment out the different regions of the human face. Face segmentation is the first step towards deep fake using GANs. It can be used in multiple projects such as face tracking, face recognition, emotion detection, etc.

**Approach to be followed (optional)**
I will use the UNet model for the task of segmentation in Tensorflow.

**Additional context**
I am GSSOC'21 participant.

**Comment by akshitagupta15june** [comment]
please add your implemetation in https://github.com/akshitagupta15june/Face-X/tree/master/Awesome-face-operations

**Comment by nandinib1999** [comment]
Thank you! :)

**Comment by akshitagupta15june** [comment]
are you still working on this issue?
