### ISSUE TITLE
Feature request : Adding Face Recognition Using Dlib

### ISSUE THREAD

**Issue by pm0824** [akshitagupta15june/Face-X#354]
**Description**
Dlib offers a deep learning based state-of-the-art face recognition feature. It is mainly based on a CNN model heavily inspired from ResNet model. Also, it covers all required stages of a modern face recognition flow including detect, align, represent and recognize.

**Additional context**
I am GSSoC'21 participant and would like work on this issue. Kindly assign it to me. Looking forward to contribute to this project.

**Comment by AdityaNikhil** [comment]
Hey @pm0824,
 Have you completed this project? If so, please save your model to integrate with [Face-X Library](https://github.com/akshitagupta15june/Face-X/issues/312). So that your model will be easy to implement with one line of code.

**Comment by pm0824** [comment]
Haven't completed yet @AdityaNikhil... Kindly assign me this issue @akshitagupta15june

**Comment by akshitagupta15june** [comment]
yes sure

**Comment by akshitagupta15june** [comment]
@pm0824 when you complete this try to implement what @AdityaNikhil ask u to do and let me know if any issue is to be added

**Comment by pm0824** [comment]
Sure, Thank you.
