### ISSUE TITLE
Create a proper readme file for awesome Face operations

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#356]
https://github.com/akshitagupta15june/Face-X/tree/master/Awesome-face-operations

Add the feature information which is implemented
This readme must contain the information regarding all the facial operations can be added here like Face swapping, Face sketch, Face ghost image etc

**Comment by srimontidutta** [comment]
Can you please assign this to me?

**Comment by akshitagupta15june** [comment]
assigning
