### ISSUE TITLE
Readme Improvement for LDA Analysis

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#365]
https://github.com/akshitagupta15june/Face-X/tree/master/Recognition-Algorithms/Recognition%20using%20LDA

Add some more information regarding LDA.

**Comment by srimontidutta** [comment]
Can I work on this?

**Comment by rajeshpanjiyar** [comment]
I want to work on this. I request you to assign me this issue. I am a participant in GSSoC21

**Comment by akshitagupta15june** [comment]
assigning
