### ISSUE TITLE
Image segmentation using color spaces 

### ISSUE THREAD

**Issue by sherin527** [akshitagupta15june/Face-X#366]
@akshitagupta15june ma'am, I want to add a python script on image segmentation using color spaces and OpenCV. I will add proper readme along with screenshots as well.
ma'am, could you assign this issue to me?

**Comment by akshitagupta15june** [comment]
ok assigning you add your implementation here https://github.com/akshitagupta15june/Face-X/tree/master/Awesome-face-operations

**Comment by sherin527** [comment]
ok ma'am.
