### ISSUE TITLE
Readme Improvement for face morphing

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#376]
https://github.com/akshitagupta15june/Face-X/tree/master/Awesome-face-operations/Face-Morphing

**Comment by Jainish-shah** [comment]
Please assign this issue to me I would like to work on the readme file...

**Comment by Jainish-shah** [comment]
@akshitagupta15june please assign !!!

**Comment by akshitagupta15june** [comment]
yup

**Comment by Vi1234sh12** [comment]
Hey, @Jainish-shah  any update on this? Are you working on this?

**Comment by Jainish-shah** [comment]
Yeah! I will be completing it today as there was a small tension of Internal exams.....

**Comment by Vi1234sh12** [comment]
> Yeah! I will be completing it today as there was a small tension of Internal exams.....

that's great! , go-ahead @Jainish-shah
