### ISSUE TITLE
Face Mask Detection Using Python

### ISSUE THREAD

**Issue by Hamza3226** [akshitagupta15june/Face-X#378]

**Comment by Aayush-hub** [comment]
@akshitagupta15june Can this be assigned to me?

**Comment by Hamza3226** [comment]
> @akshitagupta15june Can this be assigned to me?

sorry, but i am working on it.

**Comment by Aayush-hub** [comment]
> > @akshitagupta15june Can this be assigned to me?
> 
> sorry, but i am working on it.

Okay, Happy coding :)

**Comment by akshitagupta15june** [comment]
this is already implemented @Hamza3226 https://github.com/akshitagupta15june/Face-X/tree/master/Face-Mask-Detection
