### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by Sanika1999** [akshitagupta15june/Face-X#382]
**Is your documentation request related to a problem? Please describe.**
A readme file for face detection using harr cascade  is missing

**Describe the documentation you want to improved**
Add  relevant information about how to use and general information about the algorithm

**Additional context**
https://github.com/akshitagupta15june/Face-X/tree/master/Face-Detection/Face%20Detection%20using%20Haar%20Cascade

**Comment by akshitagupta15june** [comment]
you can work on it!

**Comment by Sanika1999** [comment]
Sure thanks

**Comment by Vi1234sh12** [comment]
Hey, @Sanika1999  any update on this? Are you working on this?

**Comment by Sanika1999** [comment]
> Hey, @Sanika1999  any update on this? Are you working on this?

Yes Iam working on it sorry for the delay

**Comment by Vi1234sh12** [comment]
> > Hey, @Sanika1999  any update on this? Are you working on this?
> 
> Yes Iam working on it sorry for the delay

That's Grate! @Sanika1999,  Go Head!

**Comment by akshitagupta15june** [comment]
are you still working on this issue?

**Comment by Vi1234sh12** [comment]
> > > Hey, @Sanika1999  any update on this? Are you working on this?
> > 
> > 
> > Yes Iam working on it sorry for the delay
> 
> That's Grate! @Sanika1999, Go Head!

Hey @akshitagupta15june  , @Sanika1999  are you still working on this issue? , Please let me know

**Comment by Sanika1999** [comment]
> > > > Hey, @Sanika1999  any update on this? Are you working on this?
> > > 
> > > 
> > > Yes Iam working on it sorry for the delay
> > 
> > 
> > That's Grate! @Sanika1999, Go Head!
> 
> Hey @akshitagupta15june , @Sanika1999 are you still working on this issue? , Please let me know

Hi just created a pr for this issue please check. sorry for the delays.😀
