### ISSUE TITLE
Realtime Age prediction implementation

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#387]
let me know if I have to open a discussion about this issue.

add the implementation inside this folder: https://github.com/akshitagupta15june/Face-X/tree/master/Awesome-face-operations

**Comment by ahmed-cyber** [comment]
@akshitagupta15june  I'm gssoc participant and I would like to work on this issue , please assign it to me

**Comment by EsraaAshraf99** [comment]
@akshitagupta15june  I am a GSOC participant and I would like to work on this issue. Please assign it to me

**Comment by akshitagupta15june** [comment]
assigning to @ahmed-cyber

**Comment by Sibasish-Padhy** [comment]
hello I am a gssoc participant and I wanna contribute to this issue. Can you assign the task to me as well
