### ISSUE TITLE
Readme Improvement in pencil sketch folder

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#388]
https://github.com/akshitagupta15june/Face-X/blob/master/Awesome-face-operations/Pencil%20Sketch/readme.md

**Comment by Vi1234sh12** [comment]
Please assign this issue to me I would like to work on the readme file...

**Comment by akshitagupta15june** [comment]
sure

**Comment by Vi1234sh12** [comment]
Thanks
