### ISSUE TITLE
Readme Improvement in blurring face

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#389]
https://github.com/akshitagupta15june/Face-X/tree/master/Blurring%20image%20across%20face

**Comment by Anas-Issa** [comment]
Hello. I am a gssoc'21 participant, I am interested in working on this issue. Can you assign it to me?

**Comment by manisha-27** [comment]
Hey...I'm a GSSOC'21 participant. Can you assign this issue to me??

**Comment by akshitagupta15june** [comment]
Assigning to @Anas-Issa in fcfs basis
