### ISSUE TITLE
Gender Detection

### ISSUE THREAD

**Issue by aakriti1318** [akshitagupta15june/Face-X#399]
**Is your feature request related to a problem? Please describe.**
Gender Detection on live cameras. 

**Describe the solution you'd like**
The detection is done using OpenCV and Keras.

**Describe alternatives you've considered**
This can be done on videos or on images.

Please assign me to work on this issue.

**Comment by akshitagupta15june** [comment]
Add your Implementation inside Awesome face operations

**Comment by ahmed-cyber** [comment]
HI I am GSSOS participant and I want to work on this issue with my partner 
@akshitagupta15june

**Comment by akshitagupta15june** [comment]
assigning

**Comment by EsraaAshraf99** [comment]
@akshitagupta15june  I am a GSOC , I would like to work on this issue

**Comment by akshitagupta15june** [comment]
Assigning
