### ISSUE TITLE
Connect faces with database or datasheet to recognize.

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#4]

**Comment by 0tist** [comment]
could you please provide a sample of the functionality you wish to include in the project

**Comment by akshitagupta15june** [comment]
Functionality like Connect name database with a particular person so when they are  in front of camera again there name shows , i am talking about multiple faces

**Comment by khushi0704** [comment]
Please assign me this issue ?

**Comment by akshitagupta15june** [comment]
ok
