### ISSUE TITLE
Add face detection using MTCNN algorithm

### ISSUE THREAD

**Issue by Sanika1999** [akshitagupta15june/Face-X#402]
**Is your feature request related to a problem? Please describe.**
MTCNN or Multi-Task Cascaded Convolutional Neural Networks is a neural network which detects faces and facial landmarks on images. It was published in 2016 by Zhang et al. MTCNN output example. MTCNN is one of the most popular and most accurate face detection tools today. It will be great to have this added to this project.

**Describe the solution you'd like**
A .py and jupyter notebook should be added with readme and relevant examples.

**Comment by akshitagupta15june** [comment]
assigning you please add your implementation inside this https://github.com/akshitagupta15june/Face-X/tree/master/Face-Detection

**Comment by akshitagupta15june** [comment]
are you still working on this issue?

**Comment by Sanika1999** [comment]
Yes @akshitagupta15june  sorry I got busy I will complete it asap

**Comment by akshitagupta15june** [comment]
are u working on this?

**Comment by NEERAJAP2001** [comment]
Hey @akshitagupta15june I'd like to work on this issue!
I'll follow the same solution as mentioned in the comment.
Thanks

**Comment by Sanika1999** [comment]
Hi @NEERAJAP2001 I was working on this implementation for a while and just created a pr for this. You can create a new issue there are many algorithms yet to be added. If you need help reach out on discord.

**Comment by NEERAJAP2001** [comment]
Oh! cool @Sanika1999, My Bad I thought you were busy!!
Thanks
