### ISSUE TITLE
Documentation Improvement for Cartoonify Image GUI 

### ISSUE THREAD

**Issue by Sagnik220** [akshitagupta15june/Face-X#411]
**Is your documentation request related to a problem? Please describe.**
I want to update the Documentation as I have used some more libraries to improve the GUI 

**Describe the documentation you want to improved**
1.Adding the libraries
2.Picture of Updated GUI

**Comment by akshitagupta15june** [comment]
assigning you

**Comment by AdityaGarg00** [comment]
I WOULD LIKE TO CONTRIBUTE TO THIS PROJECT
