### ISSUE TITLE
<gssoc'21> face mask detection

### ISSUE THREAD

**Issue by sayan9112** [akshitagupta15june/Face-X#419]
**FACE MASK DETECTION**
Hi admin, Sayan here. I'm  GSSoC'21 participant. I want to contribute in your project as it is more insightful.
There is no issues left  if I consider 'first come first out' open source culture.
So I have  to create a new one.
So I'm proposing **FACE MASK DETECTION** in your project. I've planned use python, keras, open CV, mobile net in this feature.

**Please assign me in this feature.**
Already I'm late for my collage midsems. 
If you want I can show demo of this feature.

**Comment by akshitagupta15june** [comment]
Hello @sayan9112 this feature is already implemented you can see the face mask folder there.
Let me know if you have some more new ideas.
