### ISSUE TITLE
Ghost Image/images path addition to get rid of uploading them

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#420]
**Is your feature request related to a problem? Please describe.**
Using the Image path instead of uploading the image to test the result and removing the axis of the final output.

**Describe the solution you'd like**
Adding an image path helps the user to flexibly test the script image without actually uploading it.

**Describe alternatives you've considered**
Direct image path instead of uploading it.

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Comment by A-kriti** [comment]
@akshitagupta15june  ma'am please assign this to me!

**Comment by akshitagupta15june** [comment]
assigning
