### ISSUE TITLE
<GSSoC'21> Iris Detection

### ISSUE THREAD

**Issue by sayan9112** [akshitagupta15june/Face-X#422]
Hi admin, Sayan here. I'm GSSoC'21 participant. I want to contribute in your project as it is more insightful.

I want to add a new feature **"Iris Detection"**.
I've implemented it already.
Please assign me to this issue so I can contribute.

**Comment by akshitagupta15june** [comment]
please add your implementation inside awesome face operations

**Comment by akshitagupta15june** [comment]
are you still working on this issue?

**Comment by sayan9112** [comment]
yes I'm working on it
