### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Ismail-Farahat** [akshitagupta15june/Face-X#423]
**Is your feature request related to a problem? Please describe.**
I will try to build a model for face detection using CNN Algorithm 

**Describe the solution you'd like**
I guess this model will be good for face detection.

**Describe alternatives you've considered**
Trying other algorithms of ML in image analysis

**Approach to be followed (optional)**
1- I will search for reliable data recourses to get more data.
2- I will clean the data and make necessary steps to make the data convenient with the algorithm.
3- I will build the CNN model using python with ML libraries.

**Comment by akshitagupta15june** [comment]
add your implementation inside this folder https://github.com/akshitagupta15june/Face-X/tree/master/Face-Detection
