### ISSUE TITLE
Feature request / face completion

### ISSUE THREAD

**Issue by walaa5** [akshitagupta15june/Face-X#429]
**Is your feature request related to a problem? Please describe.**
I will try to build a model for face completion using GANs algorithm.

**Describe the solution you'd like**
 this is a novel approach for image completion that results in images that are both locally and globally consistent.
so it will be good to complete a face image.

**Describe alternatives you've considered**
trying another CNN models.

**Additional context**
![d166bbf8-b1df-486c-821c-4855882c1231](https://user-images.githubusercontent.com/45610906/112757426-0c839000-8fea-11eb-9623-b767f0a95695.jpg)

**Comment by akshitagupta15june** [comment]
please add your implementation in awesome-face-operations

**Comment by akshitagupta15june** [comment]
are you still working on this issue?

**Comment by walaa5** [comment]
yes, but I was having a problem in training, so sorry for being late. just needed two days
