### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Aayush-hub** [akshitagupta15june/Face-X#43]
**Describe the bug**
After installing all dependencies ,code always  shows same error ***AttributeError: module 'cv2.cv2' has no attribute 'face'.***

**To Reproduce**
1. Fork the repository.
2. Run ***facial_recognition_part1.py*** to collect data.
2. Then run ***facial_recognition_part2.py***.
3. pip install opencv-contrib-python, if it shows access denied ,try uninstalling opencv-python and try again.

**Expected behavior**
After running ***facial_recognition_part2.py*** ,the model should be trained and a message should be printed ""Model Training Complete".

**Actual behavior**
After running ***facial_recognition_part2.py*** ,here the error comes **AttributeError: module 'cv2.cv2' has no attribute 'face'** 
 ,even after fulfillng all dependencies.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/65889104/103136801-a5ec8e80-46e9-11eb-8019-6dfbae00c2ef.PNG)

**Comment by akshitagupta15june** [comment]
Hi @Aayush-hub 
You need to install opencv-contrib

pip install opencv-contrib-python
It should work after that.

**Comment by Aayush-hub** [comment]
@akshitagupta15june  Already done that! But the error continues.

**Comment by akshitagupta15june** [comment]
Ok @Aayush-hub i will have a look in this.
In my pycharm it is working fine but surely i am looking at the issue.

**Comment by akshitagupta15june** [comment]
+2 for creating issue of bug report
