### ISSUE TITLE
Modify face-mask-detection-using-cnn

### ISSUE THREAD

**Issue by rajeshpanjiyar** [akshitagupta15june/Face-X#432]
Found readme of file **face-mask-detection-using-cnn** needs some improvement. So I want work on this. I am a participant in GSSoC 21.

https://github.com/akshitagupta15june/Face-X/tree/master/Face-Mask-Detection/face-mask-detection-using-cnn

**Comment by akshitagupta15june** [comment]
Assigning

**Comment by akshitagupta15june** [comment]
are you still working on this issue?

**Comment by rajeshpanjiyar** [comment]
Sorry I forget to unassign me. You can assign it to someone interested.

**Comment by ahmedtarek26** [comment]
I wanna work at this issue

**Comment by akshitagupta15june** [comment]
Ok
