### ISSUE TITLE
Readme Improvement for Cartoonification Readme File 

### ISSUE THREAD

**Issue by Vi1234sh12** [akshitagupta15june/Face-X#437]
**Is your documentation request related to a problem? Please describe.**
Cartoonification Readme File :
[Readme Improvement for Cartoonification Readme File #437 ](https://github.com/akshitagupta15june/Face-X/blob/master/Cartoonify%20Image/Cartoonification/Readme.md)

**Describe the documentation you want to improve**
- Add information related to Cartoonification how it's working behind 
- Describe code and how they function is works 
- installation process 
- required library, modules, etc.
- add high quality the image 
 
### Current State 
![Before_update1](https://user-images.githubusercontent.com/45570993/113089566-82177800-9205-11eb-9cf0-5e4a9484f90d.PNG)
 

**Additional context**

**Comment by akshitagupta15june** [comment]
assigning

**Comment by Vi1234sh12** [comment]
> assigning

Thank you!
