### ISSUE TITLE
Face Restoration

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#445]
add your implemenation awesome face operation folder
![image](https://user-images.githubusercontent.com/57909583/113438016-5a8efe00-9405-11eb-8161-0bfda76dd84e.png)

**Comment by srimontidutta** [comment]
Hi! Can I work on this issue?

**Comment by akshitagupta15june** [comment]
yes

**Comment by akshitagupta15june** [comment]
are u working on this?

**Comment by srimontidutta** [comment]
I am. Sorry, I am a bit late due to exams

**Comment by srimontidutta** [comment]
@akshitagupta15june Can you please assign me once again? I've almost completed it.

**Comment by akshitagupta15june** [comment]
ok
