### ISSUE TITLE
Face Retrieval

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#447]
![image](https://user-images.githubusercontent.com/57909583/113438303-ee60ca00-9405-11eb-8e26-28ea09b5a7fc.png)

add in awesome face operations

**Comment by Vidipta** [comment]
Hi, can I work on this for gssoc21?

**Comment by sudipg4112001** [comment]
Hey, can I work on it ?

**Comment by akshitagupta15june** [comment]
ok assigning

**Comment by akshitagupta15june** [comment]
in fcfs to @Vidipta

**Comment by Vi1234sh12** [comment]
hey @Vidipta , are you still working on this issue ,  please let known

**Comment by Vidipta** [comment]
Hi @Vi1234sh12 , yes

**Comment by Vi1234sh12** [comment]
Hey @akshitagupta15june , can I work on this Issue , please let me know

**Comment by akshitagupta15june** [comment]
ok

**Comment by ainy-123** [comment]
> ok

Thanks for assigning.
