### ISSUE TITLE
Generate Celebrity's Face using DCGAN

### ISSUE THREAD

**Issue by NEERAJAP2001** [akshitagupta15june/Face-X#457]
**Is your feature request related to a problem? Please describe.**
I'd Like to add Generating Face Project.
I would be using [This](http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html) Data set to generate faces of celebrities using DCGAN.( will be following the total pipeline)

**Describe the solution you'd like**
In this project, I'll define and train a DCGAN on a dataset of faces. the goal is to get a generator network to generate new images of faces that look as realistic as possible!
1.I'll use, CelebFaces Attributes Dataset (CelebA) to train the adversarial networks.
2.The project will be broken down into a series of tasks from loading in data to defining and training adversarial networks. 
3.At the end of the notebook, We'll be able to visualize the results of the trained Generator to see how it performs.
4.I'll add Model pkl File and Images as well.

I'd like to work on this issue as part of GSSOC-21.
Thanks

**Comment by akshitagupta15june** [comment]
please add your implementation in awesome face operations
