### ISSUE TITLE
Face detection using dlib HOG

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#46]

**Comment by Halix267** [comment]
Can I take this @akshitagupta15june

**Comment by Sameera-Aryasomayajula** [comment]
Can I please work on this issue

**Comment by bharath-acchu** [comment]
@akshitagupta15june  Can I work on this issue, under dwoc, please assign me

**Comment by akshitagupta15june** [comment]
Ok assigning you @bharath-acchu
