### ISSUE TITLE
Readme Improvement for Mosaic-Effect 

### ISSUE THREAD

**Issue by Vi1234sh12** [akshitagupta15june/Face-X#460]
** New Feature Updated Points 💯 **

- [ ]   Add Information Related Projects and Behind History 

- [ ]  Add high-resolution Image 

- [ ]  Add Installation Process 

- [ ]  Also mention which library is used 

- [ ] attached a real example so anyone can understand it properly

- [ ]  also attached resource 

**Describe the solution you'd like**
[Mosaic-Effect Code ](https://github.com/akshitagupta15june/Face-X/blob/master/Awesome-face-operations/Mosaic-Effect/Mosaic.py)

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of the approach to be followed.

**Additional context**
###  Current State : 
![Before_update2](https://user-images.githubusercontent.com/45570993/113655663-e465f200-96b7-11eb-85d1-570bdb754e86.PNG)

**Comment by akshitagupta15june** [comment]
assigning
