### ISSUE TITLE
Auto Label Bot

### ISSUE THREAD

**Issue by ankit-kmar** [akshitagupta15june/Face-X#461]
**Is your feature request related to a problem? Please describe.**
Add GitHub action to auto label issues with gssoc21 label when contributor asks to work under gssoc21. As it takes time for the maintainer to add labels, I can add a script that can auto-label issues with the gssoc21 label whenever contributors ask to work under that label.

**Describe the solution you'd like**
A script in .github folder to automate the process.

**Describe alternatives you've considered**
None

**Additional context**
Please assign me this issue with a GSSOC tag and a level tag.

**Comment by akshitagupta15june** [comment]
GitHub action are not allowed.
