### ISSUE TITLE
Main Readme File  Image Path is Update 

### ISSUE THREAD

**Issue by Vi1234sh12** [akshitagupta15june/Face-X#465]
**Describe the bug**
- [ ]  Update Image Path 
- [ ]  Add Offical Image or logo  `Images` Folder

**To Reproduce**

**Actual behavior**
Actually, Many times happens we are creating a different folder with the same images so the result is  [ File size max ] 
- please remember not to repeat the same mistakes

**Screenshots**
![Before_Update3](https://user-images.githubusercontent.com/45570993/113813011-b2728f80-978c-11eb-9005-cd762cfa7c0e.PNG)
**Additional details**

**Comment by akshitagupta15june** [comment]
i have changed it, thanks for noticing
