### ISSUE TITLE
Face Recognition Using Inception V3 model

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#469]

**Comment by Preeti2095** [comment]
I want to work on this issue.

**Comment by akshitagupta15june** [comment]
Ok

**Comment by Preeti2095** [comment]
I am not working in this issue now.

**Comment by Vi1234sh12** [comment]
hey @akshitagupta15june I want work on this issue , please let me know

**Comment by Vi1234sh12** [comment]
> hey @akshitagupta15june I want work on this issue 

Please let me know

**Comment by akshitagupta15june** [comment]
Ok

**Comment by Vi1234sh12** [comment]
> Ok

Thanks  , @akshitagupta15june
