### ISSUE TITLE
Face recognition and detection using Random forest and combination of LBP and HOG features

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#47]

**Comment by Halix267** [comment]
@akshitagupta15june  I am confused about this issue that what does it meant by combination of LBP and HOG features. Plzz resolve my query..

**Comment by akshitagupta15june** [comment]
Hi the upcoming issues are for dwoc participants

**Comment by Halix267** [comment]
Ok

**Comment by SoyabulIslamLincoln** [comment]
Hi @akshitagupta15june . I want to work on this. can you assign me this task?

**Comment by Bhagyashri2000** [comment]
Hi @akshitagupta15june   I would like to work on this issue. I'm DWoC participant.

**Comment by akshitagupta15june** [comment]
ok @Bhagyashri2000

**Comment by SinghShreya05** [comment]
Ma'am is this issue still open? I'll like to work under SWOC label. @akshitagupta15june

**Comment by akshitagupta15june** [comment]
hi @SinghShreya05 i think @Bhagyashri2000 is working on this.
