### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by KKhushhalR2405** [akshitagupta15june/Face-X#473]
**Is your feature request related to a problem? Please describe.**
I would like to implement a method for applying styles to faces using neural style transfer.

**Describe the solution you'd like**
I would use style transfer using CNNs to apply a style of one image to another image. I will extract the features and styles from the input images and will merge them to create a final styled image. I will use PyTorch for implementing it.

**Describe alternatives you've considered**
We can use GANs for transferring style from one image to another. But Using CNNs to implement style transfer is faster and computationally efficient.

**Approach to be followed (optional)**
I would follow the method described in the research paper [Image Style Transfer Using Convolutional Neural Networks](https://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Gatys_Image_Style_Transfer_CVPR_2016_paper.pdf) 

**Additional context**
I am attaching some sample screenshots.

**Input**
<a href="https://imgbb.com/"><img src="https://i.ibb.co/F66RD9B/blonde.jpg" alt="blonde" border="0" width="250px" height="250px"></a><a href="https://imgbb.com/"><img src="https://i.ibb.co/sw4x99F/delaunay.jpg" alt="delaunay" border="0" width="250px" height="250px"></a>

**Output**

<a href="https://imgbb.com/"><img src="https://i.ibb.co/bKpngDg/final-image.png" alt="final-image" border="0" width="250px" height="250px"></a>

**Comment by akshitagupta15june** [comment]
Add your implementation in awesome face operations
