### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ParthSingh0506** [akshitagupta15june/Face-X#474]
->Using Neural Network for detecting Emotion in video as well as images 

**Describe the solution you'd like**
->The basic idea is that our Neural Network will able to classify the emotion of person whether the person is happy , sad , normal ,angry . By sending the image as well as video the  NN will tell us about the emotion of a person .

**Comment by ParthSingh0506** [comment]
@akshitagupta15june Will you assign me this issue

**Comment by ParthSingh0506** [comment]
@akshitagupta15june kindly assign me this issue

**Comment by akshitagupta15june** [comment]
Hi this feature is already implemented
