### ISSUE TITLE
Glitter effect filter

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#482]
**Is your feature request related to a problem? Please describe.**
Want to apply a glitter effect to an image.

**Describe the solution you'd like**
Implementing a glitter effect using OpenCV and NumPy.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Comment by akshitagupta15june** [comment]
Assigning

**Comment by akshitagupta15june** [comment]
Add in awesome face operations
