### ISSUE TITLE
Add a readme for blurring image across face PORTRAIT MODE

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#483]
https://github.com/akshitagupta15june/Face-X/tree/master/Blurring%20image%20across%20face

**Comment by salonidabgar** [comment]
Hi! @akshitagupta15june I am a GSSOC'21 participant. Can I work on this issue?

**Comment by akshitagupta15june** [comment]
ok

**Comment by akshitagupta15june** [comment]
are u working on this?

**Comment by Vi1234sh12** [comment]
hey @akshitagupta15june  can I work on This Issue , Please let me Know 

give me a correct  directory Path

**Comment by iaryangoyal** [comment]
hi can u assign this to me

**Comment by akshitagupta15june** [comment]
ok

**Comment by iaryangoyal** [comment]
@akshitagupta15june the above link is not working

**Comment by iaryangoyal** [comment]
The above link is not working ma'am

**Comment by akshitagupta15june** [comment]
https://github.com/akshitagupta15june/Face-X/tree/master/Awesome-face-operations/Blurring%20image%20across%20face

**Comment by iaryangoyal** [comment]
#586

**Comment by iaryangoyal** [comment]
I have added some of the details of blurring. I think other things are ok. so I have added some of the detailed info of blur. if there is any issue with this please let me know I'll change it as soon as possible.
