### ISSUE TITLE
Face-x Readme Improvement

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#49]

**Comment by IshetaBansal** [comment]
Hi!
I would love to work on the Readme file. Please assign it to me. Thank you :)

**Comment by akshitagupta15june** [comment]
Yes , assigning to u

**Comment by akshitagupta15june** [comment]
Are u a dwoc participant

**Comment by IshetaBansal** [comment]
> Yes , assigning to u

Thanks a lot :)
And yes, I am a DWOC participant.

**Comment by IshetaBansal** [comment]
Any specific things you would like me to focus on? 
I would like to know what all you expect. 
Thank you :)

**Comment by akshitagupta15june** [comment]
Yes
Try to include various algorithms which are already implemented in this repo.
So that contributors can have a look at them.

**Comment by tharunc** [comment]
Hello there,
       I would like to work on the readme.md file issue . Can you please assign it to me.

**Comment by akshitagupta15june** [comment]
Hi this issue is already assigned to @IshetaBansal

**Comment by akshitagupta15june** [comment]
You can work on diff issues which are not assigned to anyone of dwoc

**Comment by akshitagupta15june** [comment]
@IshetaBansal are you working on this issue?

**Comment by IshetaBansal** [comment]
> @IshetaBansal are you working on this issue?

Yes Ma'am
It'll be complete by tomorrow evening. Sorry if it got delayed.
