### ISSUE TITLE
Add newly implemented algorithms in Comparative Study of the Algorithms

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#490]
https://github.com/akshitagupta15june/Face-X/blob/master/Recognition-Algorithms/README.md

**Comment by lekshmissunil** [comment]
Hey, I'm a GSSOC'21 participant and would like to work on this. @akshitagupta15june could you please assign this to me?

**Comment by akshitagupta15june** [comment]
Assigning

**Comment by lekshmissunil** [comment]
> Assigning

Thank you! I'm on it.

**Comment by lekshmissunil** [comment]
@akshitagupta15june I've created a pull request. Please review it asap.
