### ISSUE TITLE
Add a proper redame for attendance system

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#491]
https://github.com/akshitagupta15june/Face-X/tree/master/Facial%20Recognition%20Attendance%20Management%20System/Attendance%20system

**Comment by vanshu25** [comment]
@akshitagupta15june Mam, I am interested and would like to work on this issue. Kindly assign me this issue.

**Comment by akshitagupta15june** [comment]
Ok

**Comment by Vi1234sh12** [comment]
hey @vanshu25 , Are you still  working on this Issue , Please let me known

**Comment by vanshu25** [comment]
@Vi1234sh12 , hey I'm not working on this issue

**Comment by Vi1234sh12** [comment]
> @Vi1234sh12 , hey I'm not working on this issue

Hey  @akshitagupta15june , can I work on this Issue , please let me know

**Comment by akshitagupta15june** [comment]
Yes

**Comment by Vi1234sh12** [comment]
> Yes

Thanks !
