### ISSUE TITLE
Add 2 New Snapchat Filters 

### ISSUE THREAD

**Issue by NEERAJAP2001** [akshitagupta15june/Face-X#503]
I'd like to add 2 new filters into the Snapchat filters folder:

* Anabelle mask Filter
* Joker nose Filter

I'm sure they are not present already in the folder.

Will be using :

* Python
* The program makes use of Dlib-facial feature points
* OpenCV
* Tkinter
* Shape predictor 68 face landmark points Model

I'd like to work on this as part of the GSSOC-21.

**Comment by akshitagupta15june** [comment]
These two filters are already added

**Comment by NEERAJAP2001** [comment]
@akshitagupta15june but I did not find them (in the folder) can you please confirm?

**Comment by akshitagupta15june** [comment]
Ok you can implement a Annabelle filter

**Comment by NEERAJAP2001** [comment]
Ok, thanks!!
