### ISSUE TITLE
Readme Update Recognition-using-IOT

### ISSUE THREAD

**Issue by Vi1234sh12** [akshitagupta15june/Face-X#505]
**Is your feature request related to a problem? Please describe.**
- Add more Information related device and  IDE 
- Update images  so , Anyone can understand 
- please describe more point related library or module or 

** Link**
[Recognition-using-IOT](https://github.com/akshitagupta15june/Face-X/tree/master/Recognition-using-IOT)

**Screenshot**
![Before_update5](https://user-images.githubusercontent.com/45570993/114586281-1ec82400-9ca2-11eb-8e07-99e508bcf713.PNG)

**Comment by akshitagupta15june** [comment]
Assigning
