### ISSUE TITLE
Oil Paint Filter

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#515]
**Is your feature request related to a problem? Please describe.**
Want to apply an oil paint filter effect to an image.

**Describe the solution you'd like**
Implementing an oil paint filter effect using OpenCV and NumPy.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Comment by akshitagupta15june** [comment]
Ok assigning
