### ISSUE TITLE
Face Tracking Using Arduino

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#52]
Python does the image processing, Arduino controls the servo motors.
An awesome IOT implementation.

**Comment by smriti1313** [comment]
Hi, what are we suppose to do in this? Like provide you with a code or what?
Thanks

**Comment by akshitagupta15june** [comment]
Yes all implementation

**Comment by smriti1313** [comment]
As per my knowledge regarding python and arduino, then there will be one file having python code and other arduino code. I can include software requirements and libraries used. Is there anything that i am missing?

**Comment by akshitagupta15june** [comment]
Yes correct
Try to make a good readme showing all procedures+ output

**Comment by smriti1313** [comment]
I got your points. How am i suppose to show output?I have no hardwares right now. I will be going to try for this issue so can you assign this to me please? Thank you

**Comment by smriti1313** [comment]
Hi, I have seen project mentors giving "dwoc-accepted" label. I have no idea about this but i guess that its necessary for dwoc participants. Kindly check for that. Thank you for giving me a chance

**Comment by akshitagupta15june** [comment]
Let me ask from organizer.

**Comment by akshitagupta15june** [comment]
@smriti1313 can you please tell me which repo had dwoc-accepted tag?

**Comment by smriti1313** [comment]
> 
> 
> @smriti1313 can you please tell me which repo had dwoc-accepted tag?

Yeah. check [this](https://github.com/swapnilsparsh/Rescue/issues?q=is%3Aissue+is%3Aclosed)
