### ISSUE TITLE
Document improvement

### ISSUE THREAD

**Issue by vanshu25** [akshitagupta15june/Face-X#526]
Is your documentation request related to a problem? Please describe.
The readme file for Style readme needs to be improved.

**Describe the documentation you want to improve**
Add more examples and images for style transfer, a little bit more about working of style transfer and its importance and prerequisites

**Additional context**
https://github.com/akshitagupta15june/Face-X/tree/master/Awesome-face-operations/Style-Transfer

@akshitagupta15june ma'am I would like to update readme file of style transfer.

**Comment by akshitagupta15june** [comment]
Ok

**Comment by akshitagupta15june** [comment]
are u working on this?

**Comment by vanshu25** [comment]
Yes, I'm working on this.. It's almost completed
