### ISSUE TITLE
Readme Improvement in Main Readme File Face-x 

### ISSUE THREAD

**Issue by Vi1234sh12** [akshitagupta15june/Face-X#528]
**Is your feature request related to a problem? Please describe.**
-  Update Readme File with Features 
- Add new Points 

[Link](https://github.com/akshitagupta15june/Face-X)

**Comment by akshitagupta15june** [comment]
Ol

**Comment by Vi1234sh12** [comment]
hey @akshitagupta15june  , I'm  Share Screenshot ,  Let me know if you have any Changes , then I'm create pull request 

see screenshot 

![Check_main readme](https://user-images.githubusercontent.com/45570993/115433860-a45d4e00-a225-11eb-9bce-6a47cce1b877.PNG)

![Check_main readme1](https://user-images.githubusercontent.com/45570993/115433902-b0491000-a225-11eb-875f-fc6e722daa1e.PNG)

![check_main readme2](https://user-images.githubusercontent.com/45570993/115433934-b63ef100-a225-11eb-8f82-f33be86d7f9c.PNG)

**Comment by akshitagupta15june** [comment]
You have to put same logo of face-x and that animation

**Comment by akshitagupta15june** [comment]
Can you change that

**Comment by Vi1234sh12** [comment]
> Can you change that

Sorry , But I have no Idea  so , I can't change this
