### ISSUE TITLE
Cartoonifying a face image

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#53]
Converting a facial Image to Cartoon Using OpenCV

Some basic steps.

importing libraries
Reading the input image
Detecting edges in the image
Converting into grayscale & applying the medium blur
Cartoonifying the image

**Comment by SoyabulIslamLincoln** [comment]
I want to work on this issue.

**Comment by SoyabulIslamLincoln** [comment]
Can I work on more than one issues?

**Comment by akshitagupta15june** [comment]
Assigning to u

**Comment by akshitagupta15june** [comment]
Are u a dwoc participant?

**Comment by SoyabulIslamLincoln** [comment]
Yes I am DWOC particiapnt.

**Comment by SoyabulIslamLincoln** [comment]
Yes I am dwoc participant.

**Comment by SoyabulIslamLincoln** [comment]
Can i apply for another issue @akshitagupta15june ?

**Comment by akshitagupta15june** [comment]
Yes let me know

**Comment by SoyabulIslamLincoln** [comment]
I have a question. I am new to open source contribution. I have pulled a request to merge. And merged it. The uploaded file is showing in the git repo that I forked from you. But not in maser branch. It would be very kind if you make me understand the process.

**Comment by akshitagupta15june** [comment]
Yeah the file which u have to merged it should to akshitagupta15june@gmail: master

**Comment by akshitagupta15june** [comment]
Like i am showing you a screenshot of pr
![Uploading Screenshot_2020-12-27-21-40-06-714_com.android.chrome~2.jpg…]()

**Comment by SoyabulIslamLincoln** [comment]
Hello @akshitagupta15june . I have resolved the problem. If you check that and tell me, it would be great.

**Comment by akshitagupta15june** [comment]
@SoyabulIslamLincoln Awesome work!

Yes i have seen it and will merge your pr.
I will not close issue because more contributor will like to implement it with new features.

**Comment by akshitagupta15june** [comment]
And regardling points that willl be updated in backend by the organisers of dwoc.

**Comment by SoyabulIslamLincoln** [comment]
That's great. I will also work on it for creating a web app like one can upload their image and video , cartoonify it and download it. Do I have permission to work ma'am?

**Comment by akshitagupta15june** [comment]
Great idea!
I am creating an issue and will assign it to u

**Comment by akshitagupta15june** [comment]
Yeah a GUI will be perfect for this

**Comment by SoyabulIslamLincoln** [comment]
It is very kind of you. Thanks a lot.

**Comment by amandp13** [comment]
@akshitagupta15june Ma'am I would like to work on this issue as a part of SWOC 2021.

**Comment by akshitagupta15june** [comment]
ok

**Comment by rawCode4U** [comment]
@akshitagupta15june  please assign this issue to me i want to work on it

**Comment by akshitagupta15june** [comment]
OK @rawCode4U 
are you an dwoc or swoc or nwoc participant?

**Comment by rawCode4U** [comment]
I am DWOC participant

**Comment by akshitagupta15june** [comment]
ok @rawCode4U
