### ISSUE TITLE
Image Registration

### ISSUE THREAD

**Issue by Saptar001** [akshitagupta15june/Face-X#545]
Hello @akshitagupta15june , I would like to work on this issue "Image Registration" using homography .
Can you please assign me the same for gssoc,21 ?

**Comment by akshitagupta15june** [comment]
Please tell me more about it

**Comment by Saptar001** [comment]
@akshitagupta15june 
Here, I would take a wrapped or morphed image and register/match the image with the reference image.

I would be comparing  the key-points and descriptors of the both wrapped and the reference image using ORB

**Comment by akshitagupta15june** [comment]
Ok add your implementation inside awesome face operations folder

**Comment by akshitagupta15june** [comment]
are u working on this?

**Comment by Saptar001** [comment]
@akshitagupta15june  yess, I am .
I have finished with the coding section, and now I have started to work on the Readme( documentation) part.
