### ISSUE TITLE
Add Cat Mask Filter as Snapchat Filter

### ISSUE THREAD

**Issue by NEERAJAP2001** [akshitagupta15june/Face-X#547]
Here is The filter : 

![cats](https://user-images.githubusercontent.com/65017645/115955089-3a3cf580-a512-11eb-8885-665f524dbafb.png)

Will be using :

* Python
* The program makes use of Dlib-facial feature points
* OpenCV
* Tkinter
* Shape predictor 68 face landmark points Model

I'd like to work on this as part of the GSSOC-21.

**Comment by akshitagupta15june** [comment]
ok
