### ISSUE TITLE
Cropping the face from an image

### ISSUE THREAD

**Issue by ShubhamGupta577** [akshitagupta15june/Face-X#566]
## Cropping the face from an image
By using this script we are going to extract out the faces from the image crop them and save as a new file.
## Approach to be followed
We are going to recognize the faces in the image by using the haarcascade algorithm and after that, by using OpenCV we are going to crop the faces from the image.

**Comment by akshitagupta15june** [comment]
Hi this is not required for this repo because this script is already included in many code present here
