### ISSUE TITLE
Add an Image to Pencil Sketch Converter

### ISSUE THREAD

**Issue by Manasi2001** [akshitagupta15june/Face-X#571]
**Is your feature request related to a problem? Please describe.**
Usually programs built like this give an outline of the image in the name of sketch, it does not look realistic.

**Describe the solution you'd like**
My program can successfully convert a RGB image into a realistic pencil sketch in 4 easy steps!

**Additional context**
Here's an example:
### Before
![img](https://user-images.githubusercontent.com/68627617/117622031-d3fdd700-b18f-11eb-8f8d-7aa655027bb1.jpg)

### After
![img4](https://user-images.githubusercontent.com/68627617/117622049-da8c4e80-b18f-11eb-859d-a16b8f9a2df8.jpg)

**Comment by akshitagupta15june** [comment]
add your implementation inside this folder https://github.com/akshitagupta15june/Face-X/tree/master/Awesome-face-operations/Colorful%20Sketch%20Filter
