### ISSUE TITLE
Adding Funny Mirror images using opencv

### ISSUE THREAD

**Issue by sherin527** [akshitagupta15june/Face-X#574]
Hello @akshitagupta15june ma'am, I want to implement Funny mirror images using OpenCV. Please assign me this I am a gssoc21 participant.

**Comment by sherin527** [comment]
@akshitagupta15june ma'am, in which folder I should add this file?

**Comment by akshitagupta15june** [comment]
in awesome face operations

**Comment by sherin527** [comment]
ok.
