### ISSUE TITLE
Add Face Recognition using VGG-Face.

### ISSUE THREAD

**Issue by NEERAJAP2001** [akshitagupta15june/Face-X#584]
About: It is one of the most popular and widely used facial recognition models and recorded 98.78% accuracy for Labeled Faces in the Wild dataset. It also had 68.17% accuracy on the masked-faced dataset called RMFRD.

Steps to follow in the project : 

Step 1: Dataset acquisition
Step 2: Detect faces.(will be using dlib)
Step 3: Download and load VGG_face weights.
Step 4: Get embeddings for faces.
Step 5: Train Softmax regressor for 6 person classification from embeddings.

I'd Like to work on this as part of the GSSOC-21.

**Comment by NEERAJAP2001** [comment]
Any Updates @akshitagupta15june?

**Comment by akshitagupta15june** [comment]
Ok assigning

**Comment by akshitagupta15june** [comment]
Add in face recognition algorithms folder
