### ISSUE TITLE
Add New Snap Chat Filter 

### ISSUE THREAD

**Issue by NEERAJAP2001** [akshitagupta15june/Face-X#589]
I'd like to add a new filter into the Snapchat filters folder:

Filter : ( I will be using cropped version ) 
![this](https://user-images.githubusercontent.com/65017645/118666989-3cdcf300-b811-11eb-8fbc-412d9e87983c.png)

We, Will, be using :

* Python
* The program makes use of Dlib-facial feature points
* OpenCV
* Tkinter
* Shape predictor 68 face landmark points Model

I'd like to work on this as part of the GSSOC-21.

**Comment by akshitagupta15june** [comment]
I think moustache filter is already present you can work on different filter
