### ISSUE TITLE
Add a new Snap Chat Filter 

### ISSUE THREAD

**Issue by NEERAJAP2001** [akshitagupta15june/Face-X#592]
I'd like to add a new Witch filter into the Snapchat filters folder:

Filter : ( I will be using cropped version )
![witch](https://user-images.githubusercontent.com/65017645/119020992-8584df80-b9bc-11eb-983c-5af2c6c86288.png)

We, Will, be using :

* Python
* The program makes use of Dlib-facial feature points
* OpenCV
* Tkinter
* Shape predictor 68 face landmark points Model
I'd like to work on this as part of the GSSOC-21.

**Comment by akshitagupta15june** [comment]
Ok assigning you
