### ISSUE TITLE
implementing different techniques in opencv for adjusting contrast in images.

### ISSUE THREAD

**Issue by ainy-123** [akshitagupta15june/Face-X#593]
1. Histogram Equalization
2. CLAHE

**Comment by ainy-123** [comment]
> 1. Histogram Equalization
> 2. CLAHE

I am GSSoC'21 participant and I want to work on this issue.
Kindly assign this to me.

**Comment by akshitagupta15june** [comment]
Hi @ainy-123 these are not related to operations on faces so we can't include in this repo
