### ISSUE TITLE
Adding filters using opencv for enhancing image

### ISSUE THREAD

**Issue by ainy-123** [akshitagupta15june/Face-X#601]
- [1] median filter.
- [2] bilateral filter.

**Comment by ainy-123** [comment]
> * [1] median filter.
> * [2] bilateral filter.

hey @akshitagupta15june ,I am GSSoC'21 participant and I want to work on this issue.
Will you please assign this to me?

**Comment by akshitagupta15june** [comment]
These filters are already implemented
