### ISSUE TITLE
Add Face Clustering

### ISSUE THREAD

**Issue by NEERAJAP2001** [akshitagupta15june/Face-X#605]
Face clustering we need to perform unsupervised learning — we have only the faces themselves with no names/labels. From there we need to identify and count the number of unique people in a dataset.

As a quick breakdown, here is everything you’ll need in your Python environment:
* OpenCV
* dlib
* imutils
* scikit-learn

I'd Like to work on this as part of GSSOC-21.

**Comment by akshitagupta15june** [comment]
Assigning
Add your implementation in awesome face operations
