### ISSUE TITLE
Neon Effect Filter

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#606]
**Is your feature request related to a problem? Please describe.**
Want to apply a "Neon Effect Filter" on an image.

**Describe the solution you'd like**
Implementing a neon effect filter using OpenCV, Matplotlib, Os and NumPy.

**Final Output**

![Screenshot (396)](https://user-images.githubusercontent.com/73133055/119267787-ad1eb680-bc0d-11eb-850a-5339b027e255.png)

**Comment by akshitagupta15june** [comment]
Ok assigning
