### ISSUE TITLE
Image Contrast Increasing Filter

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#607]
**Is your feature request related to a problem? Please describe.**
Images captured in dim light mostly have not much better contrast so an (Image Contrast increasing filter) filter helps accordingly to adjusts and increase its contrast and hence having a better version of the image.

**Describe the solution you'd like**
Using some of the python libraries to implement this feature in which matplotlib, 
IPython.display, NumPy, and PIL are used.

**Comparison between 2 images**

![Screenshot (392)](https://user-images.githubusercontent.com/73133055/119268088-f8859480-bc0e-11eb-99b4-986b2c720988.png)

**Comment by akshitagupta15june** [comment]
This filter is not required
