### ISSUE TITLE
Collobrating Tkinter GUI for face recognistion using LBPH(Feature request)

### ISSUE THREAD

**Issue by saiharsha-22** [akshitagupta15june/Face-X#61]
Can create a small Graphical user interface were, using Tkinte. Were it will be easy for the user to use the  sytstem. I would like to add GUI for face recongnisiton using LBPH algo

For Sample GUI:
![Screenshot (121)](https://user-images.githubusercontent.com/61947484/103216234-8b115880-493b-11eb-9a76-973a4bbe8cd1.png)

**Comment by saiharsha-22** [comment]
@akshitagupta15june  I am participant of Swoc 2021. If it finds useful can assign this issue to me, I would like to work on this.

**Comment by akshitagupta15june** [comment]
That will we Great you can work in this
Assigning to u.

**Comment by akshitagupta15june** [comment]
As the program will be starting from 5th jan so pr will be merged after that.

**Comment by saiharsha-22** [comment]
@akshitagupta15june  I will start working on the issue now and I will send pull request on jan 5th.

**Comment by akshitagupta15june** [comment]
Awesome

**Comment by saiharsha-22** [comment]
@akshitagupta15june 

Can you please check the GUI setup and Working of GUI once. I have attached a video below, and let me know if any changes required.
https://user-images.githubusercontent.com/61947484/103528536-265d7d00-4eaa-11eb-8b38-e1c68b9d1be2.mp4

**Comment by akshitagupta15june** [comment]
awesome @saiharsha-22

**Comment by akshitagupta15june** [comment]
keep going!

**Comment by saiharsha-22** [comment]
@akshitagupta15june  any modifications? required?. Because tomorrow I would like to send a pull request. For Pull Request should I make a new folder for this project or in any existing folder?

**Comment by akshitagupta15june** [comment]
please create a new folder

**Comment by saiharsha-22** [comment]
@akshitagupta15june  Ok I will create a new Folder named. GUI_for_Face Recognistion_using_LBPH_algo is it fine?

**Comment by akshitagupta15june** [comment]
yup

**Comment by saiharsha-22** [comment]
@akshitagupta15june I have sent PULL Request #88
