### ISSUE TITLE
Glitter Cartoon Filter

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#611]
**Is your feature request related to a problem? Please describe.**
Want to apply a "Glitter Cartoon Filter" on an image.

**Describe the solution you'd like**
Using python libraries to Implement a "Glitter Cartoon Filter". ( OpenCV, Matplotlib, Os, and NumPy)

**Final Output**

![Screenshot (399)](https://user-images.githubusercontent.com/73133055/119273215-7f466b80-bc27-11eb-8b4c-cb37462edd08.png)

**Comment by akshitagupta15june** [comment]
add your implementation in this https://github.com/akshitagupta15june/Face-X/tree/master/Cartoonify%20Image
