### ISSUE TITLE
Crayon Portrait Filter

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#612]
**Is your feature request related to a problem? Please describe.**
Want to apply a "Crayon Portrait Filter" on an image.

**Describe the solution you'd like**
Implementing a "Crayon Portrait Filter" using some of the python library functions which are OpenCV, Os, Matplotlib, and NumPy.

**Final Output**

![Screenshot (400)](https://user-images.githubusercontent.com/73133055/119273328-072c7580-bc28-11eb-9678-9684bc64608d.png)

**Comment by akshitagupta15june** [comment]
hi this is already implemented

**Comment by A-kriti** [comment]
okay
