### ISSUE TITLE
Add Face Recognition using LBPH Algorithm

### ISSUE THREAD

**Issue by NEERAJAP2001** [akshitagupta15june/Face-X#615]
Introduction and Working: Face recognition is performed using local binary pattern histograms(lbph) and face detection has been done using viola jones haar cascade classifier. The user has to first run facerecognition.py to register his face by selecting 1 to train the algorithm followed by entering password and name. The algorithm takes 64 images of the user and stores in a folder called a database. The algorithm then runs LBPH on the images and stores the trained classifier in trainedRec.py. The user can then select recognize to test whether he is an authorized person or not. The threshold posed by the condition if (prediction[1])<100 should be adjusted to adjust the sensitivity of face recognition.

I'd like to work on this issue as part of GSSOC-21

**Comment by akshitagupta15june** [comment]
This is already available
