### ISSUE TITLE
Chalk  Portrait Filter

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#617]
**Is your feature request related to a problem? Please describe.**
Want to apply a "Chalk  Portrait Filter" on an image.

**Describe the solution you'd like**
Using python libraries to Implement a "Chalk  Portrait Filter". ( OpenCV, Matplotlib, Os, and NumPy)

**Final Output**
![Screenshot (409)](https://user-images.githubusercontent.com/73133055/119375191-271b7200-bcd8-11eb-8b15-ca2720faca67.png)

**Comment by akshitagupta15june** [comment]
Hi this is already available
