### ISSUE TITLE
Detect facial biometric

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#62]
Detect eyes, nose, lips, and jaw with dlib, OpenCV, and Python

After detection draw a rectangle at every biometric.

Give a proper readme file explaining the procedure.

**Comment by Aayush-hub** [comment]
I want to work on it. Can you please assign me this?

**Comment by Aayush-hub** [comment]
@akshitagupta15june I want to work on it. Can you please assign me this?

**Comment by akshitagupta15june** [comment]
@Aayush-hub This issue is for swoc participants.

**Comment by Aayush-hub** [comment]
@akshitagupta15june Mam, I am also a SWOC participant.

**Comment by akshitagupta15june** [comment]
Oh ok I am sorry. I am assigning it to u

**Comment by Aayush-hub** [comment]
@akshitagupta15june Mam can I work on more than 1 issue? As I want to also work on #63 Emotion Recognition from the same code base.

**Comment by Aayush-hub** [comment]
@akshitagupta15june Mam , Can I submit PR for this issue before 5th January 2021?

**Comment by Aayush-hub** [comment]
@akshitagupta15june  Mam, can I create PR before 5th Jan. 2021?, so that I can work on other issues too!. Will it be counted towards SWOC's successfull contribution??

**Comment by akshitagupta15june** [comment]
yes you can create but it will be merged after 5th jan

**Comment by SinghShreya05** [comment]
@akshitagupta15june Ma'am I'll like to contribute in this issue, if it's still open, please assign me.

**Comment by Aayush-hub** [comment]
@SinghShreya05 @akshitagupta15june  I have worked on it and will make PR soon!
