### ISSUE TITLE
Frame Filter

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#620]
**Is your feature request related to a problem? Please describe.**
Want to apply a "Frame Filter" on an image.

**Describe the solution you'd like**
Using "PIL" python libraries to Implement a "Frame Filter". 

**Output**
![new](https://user-images.githubusercontent.com/73133055/119493981-69978a00-bd7e-11eb-9c36-97123a162ef5.png)

**Comment by akshitagupta15june** [comment]
Add in awesome face operations
