### ISSUE TITLE
Add Face Alignment in Face Operations

### ISSUE THREAD

**Issue by NEERAJAP2001** [akshitagupta15june/Face-X#621]
Dependency
*  imutils
*  dlib
*  opencv-python

Here we will be : 
* Identifying the geometric structure of faces in digital images.
* Attempting to obtain a canonical alignment of the face based on translation, scale, and rotation.

**Comment by akshitagupta15june** [comment]
Hi this is already implemented

**Comment by NEERAJAP2001** [comment]
@akshitagupta15june  I did not find it so I raised an issue
Thanks

**Comment by NEERAJAP2001** [comment]
@akshitagupta15june can you please confirm I did not find it in Awesome face operations.
