### ISSUE TITLE
Krishna Cartoon Filter 

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#623]
**Is your feature request related to a problem? Please describe.**
Want to apply a "Krishna Cartoon Filter" to an image.

**Describe the solution you'd like**
Using python libraries to Implement a "Krishna Cartoon Filter". ( PIL, OpenCV, Matplotlib, Os, and NumPy)

**Final Output**

![Screenshot (413)](https://user-images.githubusercontent.com/73133055/119541846-85198980-bdac-11eb-8422-8b784a460622.png)

**Comment by akshitagupta15june** [comment]
Hi this is not required.
