### ISSUE TITLE
Pepper Effect Filter

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#625]
**Is your feature request related to a problem? Please describe.**
Want to apply a "Pepper Effect Filter" on an image.

**Describe the solution you'd like**
Using python libraries to Implement a "Pepper Effect Filter". ( OpenCV, Matplotlib, Os, PIL, and NumPy)

**Final Output**

![Screenshot (419)](https://user-images.githubusercontent.com/73133055/119606131-99db3900-be0f-11eb-9022-79f51403aae9.png)

**Comment by akshitagupta15june** [comment]
hi its not required!
