### ISSUE TITLE
Emboss Effect Filter

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#627]
**Is your feature request related to a problem? Please describe.**
Want to apply an "Emboss Effect Filter" on an image.

**Describe the solution you'd like**
Using python libraries to Implement an "Emboss Effect Filter". ( Matplotlib and PIL)

**Final Output**

![Screenshot (425)](https://user-images.githubusercontent.com/73133055/119610572-13c2f080-be17-11eb-9a7d-fbffdabbc9f6.png)

**Comment by akshitagupta15june** [comment]
hi its not required!
