### ISSUE TITLE
Realtime Emotion recognition.

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#63]
Realtime Emotion recognition using facial expressions analysis.

**Comment by Aayush-hub** [comment]
@akshitagupta15june Can you please assign me this issue?. I want to work on it.

**Comment by aditi-saxena-1206** [comment]
I wish to work on this issue as part of SWOC.

**Comment by akshitagupta15june** [comment]
ok assigned to u

**Comment by TanweerulHaque** [comment]
Can I proceed with the same, I can do the work. I am an SWoC participant @akshitagupta15june  ??

**Comment by akshitagupta15june** [comment]
hi @TanweerulHaque  i think @aditi-saxena-1206 is working on this.

**Comment by aditi-saxena-1206** [comment]
Yeah I am. Just trying to get a better accuracy.

**Comment by TanweerulHaque** [comment]
Can I do it ?? @akshitagupta15june if it's still not done. I am an SwoC participant.

**Comment by aditi-saxena-1206** [comment]
I'm almost done with it. Will be adding it soon.

**Comment by Amit366** [comment]
Is this issue open??
