### ISSUE TITLE
Canny edge Detection 

### ISSUE THREAD

**Issue by Balpreetkaur291** [akshitagupta15june/Face-X#632]
**Is your feature request related to a problem? Please describe.**
Canny edge detector works on a multi-stage algorithm to detect a wide range of edges in images. 

I want to add the implementation of canny edge detection on images using openCV and python. This can be added in Awesome-face-operations 

Final Output:
![image](https://user-images.githubusercontent.com/53484794/119814583-31bc4e00-bf08-11eb-9e09-0bf12c938677.png)

**Comment by akshitagupta15june** [comment]
Hi this is not required in this repo
