### ISSUE TITLE
Crown Snapchat Filter

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#633]
**Is your feature request related to a problem? Please describe.**
Want to apply a "Crown Snapchat Filter" on an image.

**Describe the solution you'd like**
Using python libraries to Implement a "Crown Snapchat Filter". ( OpenCV, Matplotlib)

**Output**
![image](https://user-images.githubusercontent.com/73133055/119826228-700c3a00-bf15-11eb-9923-27ce76d9499d.png)

**Comment by akshitagupta15june** [comment]
Hi this is not required in this repo it is already available
