### ISSUE TITLE
Cool Snapchat Filter

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#634]
**Is your feature request related to a problem? Please describe.**
Want to apply a "Cool Snapchat Filter" on an image.

**Describe the solution you'd like**
Using python libraries to Implement a "Cool Snapchat Filter". ( OpenCV and Matplotlib)

**Output**
![image](https://user-images.githubusercontent.com/73133055/119829317-be6f0800-bf18-11eb-8f40-840b075ff3e1.png)

**Comment by akshitagupta15june** [comment]
Hi this is not required in this repo as this is already available
