### ISSUE TITLE
Pirates Filter

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#635]
**Is your feature request related to a problem? Please describe.**
Want to apply a "Pirates Filter" on an image.

**Describe the solution you'd like**
Using python libraries to Implement a "Pirates Filter". ( OpenCV and Matplotlib)

**Output**
![image](https://user-images.githubusercontent.com/73133055/119840999-114dbd00-bf23-11eb-9a7d-2d82fa17ce61.png)

**Comment by akshitagupta15june** [comment]
Hi this is not required in this repo as this is already available
