### ISSUE TITLE
Holi Festival Filters

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#640]
**Is your feature request related to a problem? Please describe.**
Want to add holi festival filters to an image.

**Describe the solution you'd like**
Using python libraries to Implement this.

**Comment by akshitagupta15june** [comment]
good

**Comment by akshitagupta15june** [comment]
try to craete different issues for different filter will assign you score according to per filter you add

**Comment by akshitagupta15june** [comment]
Here you can add holi filter just rename the issue
