### ISSUE TITLE
Forehead Jewellery Filter

### ISSUE THREAD

**Issue by A-kriti** [akshitagupta15june/Face-X#641]
**Is your feature request related to a problem? Please describe.**
Want to apply a "Forehead Jewellery Filter" on an image.

**Describe the solution you'd like**
Using python libraries to Implement a "Forehead Jewellery Filter". ( OpenCV and Matplotlib)

**Output**
![image](https://user-images.githubusercontent.com/73133055/119954949-2840ed80-bfbd-11eb-9455-f47f1abf8c44.png)

**Comment by akshitagupta15june** [comment]
if more jwellery crops can be added then its good like necklace and earings

**Comment by A-kriti** [comment]
> if more jwellery crops can be added then its good like necklace and earings

Ok I'll try
