### ISSUE TITLE
Face feature identification

### ISSUE THREAD

**Issue by swathika1** [akshitagupta15june/Face-X#659]
**Is your feature request related to a problem? Please describe.**
Recognizing face features like mouth, eyes, eyebrows, jaw and nose.

**Describe the solution you'd like**
Using OpenCV and a pre trained frontal face detector from dlib library and use it to obtain and highlight the features of the face.

**Additional context**
Opening this issue as GSSOC' 21 participant.
Please assign this to me if you approve @akshitagupta15june!

**Comment by akshitagupta15june** [comment]
this already implemented

**Comment by swathika1** [comment]
But ill be using dlib... the other one has been implemented with CNN

**Comment by akshitagupta15june** [comment]
Add your implementation inside face detection folder

**Comment by swathika1** [comment]
sure!
