### ISSUE TITLE
Develop a Python GUI for displaying Results.

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#7]
Develop a Python GUI for displaying Results.
A Interactive GUI application using python (Tkinter) to show results

**Comment by khushi0704** [comment]
hey there ! I want to do this task . Can you assign me this ?

**Comment by akshitagupta15june** [comment]
ok @khushi0704

**Comment by akshitagupta15june** [comment]
Join Discord channel for discussion.
discord.gg/f9jftkcw

**Comment by khushi0704** [comment]
yeah , will join asap !

**Comment by khushi0704** [comment]
@akshitagupta15june Hey I am trying to join to the discord group invite link but it shows invite invalid. Can you send it again ?

**Comment by akshitagupta15june** [comment]
@khushi0704 https://discord.gg/rhh3kt89 here is the link

**Comment by ashwani-rathee** [comment]
@akshitagupta15june can I work on this?No PR has been submitted in last 15 days

**Comment by akshitagupta15june** [comment]
ok
