### ISSUE TITLE
Add greetings action 

### ISSUE THREAD

**Issue by musavveer** [akshitagupta15june/Face-X#71]
I would like to add a Github Action for greeting new contributors with :
- New PR
- New Issue
Do assign it to me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
Awesome! so you are a nwoc or swoc or dwoc participant?
let me know

**Comment by musavveer** [comment]
DWOC

**Comment by musavveer** [comment]
Include DWOC Label

**Comment by akshitagupta15june** [comment]
sure

**Comment by akshitagupta15june** [comment]
is it ok @musavveer

**Comment by musavveer** [comment]
> is it ok @musavveer 

Thanks 😊
