### ISSUE TITLE
Birthday Filters

### ISSUE THREAD

**Issue by ainy-123** [akshitagupta15june/Face-X#735]
**Is your feature request related to a problem? Please describe.**
Want to apply birthday filters to an image.

**Describe the solution you'd like**
Will be using python libraries to implement this feature.

**Comment by Komal-99** [comment]
I would like to work over this issue being a gssoc participant

**Comment by ainy-123** [comment]
> I would like to work over this issue being a gssoc participant

Go ahead @Komal-99 . If you want, you can work . I am not working on this issue currently.

**Comment by Komal-99** [comment]
Ok thanks
