### ISSUE TITLE
Recognition using SIFT algorithm

### ISSUE THREAD

**Issue by rsrkpatwari1234** [akshitagupta15june/Face-X#75]
Scale Invariant Feature Transform is an important algorithm in Computer Vision for describing the local features of an image.I tested it for applying localisation using feature detection. 

https://en.wikipedia.org/wiki/Scale-invariant_feature_transform provides the rough idea of this method. I think we should try out this algorithm for face detection as well

**Comment by rsrkpatwari1234** [comment]
@akshitagupta15june I would like to work on this issue under Njack IIT Patna.Please assign it to me.

**Comment by akshitagupta15june** [comment]
sure

**Comment by mehabhalodiya** [comment]
This is already done in #145 
You can check it out here:
[Recognition using SIFT](https://github.com/akshitagupta15june/Face-X/tree/master/Recognition-Algorithms/Recognition%20using%20SIFT)

**Comment by akshitagupta15june** [comment]
oh thanks for identifying!
