### ISSUE TITLE
Facial recognition using SURF 

### ISSUE THREAD

**Issue by rsrkpatwari1234** [akshitagupta15june/Face-X#77]
SURF is another robust algortihm used for robust classification of 3d constructions.

We should try out this algorithm as well for recognising facial expressions

Reference : https://people.ee.ethz.ch/~timofter/publications/Knopp-ECCV-2010.pdf

**Comment by rsrkpatwari1234** [comment]
@akshitagupta15june I would like to work on this issue  under Njack IIT Patna. Please assign this issue to me.

**Comment by akshitagupta15june** [comment]
sure i am assigning

**Comment by bharath-acchu** [comment]
can i work on this issue @akshitagupta15june

**Comment by akshitagupta15june** [comment]
ok you can work on it.
Are you a swoc or dwoc or jwoc participant?

**Comment by bharath-acchu** [comment]
dwoc participant

**Comment by akshitagupta15june** [comment]
ok great

**Comment by akshitagupta15june** [comment]
Creating a new one!
Closing this
