### ISSUE TITLE
Adding Comparative study of all algorithms in Readme

### ISSUE THREAD

**Issue by rsrkpatwari1234** [akshitagupta15june/Face-X#78]
Different algortihms have been used for facial recognition and expression analysis. I want to add a comparative study of all these algorithms in Readme to show working on the current data set.

**Comment by rsrkpatwari1234** [comment]
@akshitagupta15june please assign this issue and its opening scores to me under njack it patna

**Comment by akshitagupta15june** [comment]
ok

**Comment by rsrkpatwari1234** [comment]
Hey @akshitagupta15june !! Can you please provide me the score for generating the 3 issues till then under njack iit patna ? Since it is about to end, idk if I will be able to generate the PR by then. In that case, you can give me scores for PR under swoc separately. Please let me know if this works ?

**Comment by akshitagupta15june** [comment]
ok i will give them 2+2+2=6

**Comment by sagnik1511** [comment]
Hello @akshitagupta15june  I want to contribute in this issue #78. Please assign me.

**Comment by akshitagupta15june** [comment]
ok @sagnik1511 assihning you
