### ISSUE TITLE
Bug report in Rainbow_filter

### ISSUE THREAD

**Issue by Komal-99** [akshitagupta15june/Face-X#796]
**Describe the bug**
While detecting mouth using mouth.xml file and then pasting filter pic over it it is placing  the pic  next to right of nose.I am not able to identify. The coordinates reason but without that image it is detecting mouth correctly
**To Reproduce**
1.  Check coordinates of for loop 
2. Correct the code

**Expected behavior**
That rainbow pic should come from above your mouth 

**Actual behavior**
The rainbow pic comes inn right of mouth
**Screenshots**

**Additional details**

**Comment by rudranshsharma123** [comment]
Hello, I would love to work on this issue. I am a participant of LGM-SOC. What exactly needs to be done here? From reading the content I could see that there is an issue with the placement of the faces? So, I would just need to fix the placement of the filter?

**Comment by rudranshsharma123** [comment]
I have fixed this issue please review this PR and let me know if I would be needing to anything else!
