### ISSUE TITLE
Recognition using CNN

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#8]
Facial Recognition using Convolutional Neural Networks

**Comment by Halix267** [comment]
Can I work on this issue @akshitagupta15june

**Comment by akshitagupta15june** [comment]
ok @Halix267

**Comment by akshitagupta15june** [comment]
Join Discord channel for discussion.
discord.gg/f9jftkcw

**Comment by Halix267** [comment]
Ok

**Comment by Halix267** [comment]
@akshitagupta15june when i try to join your discord, It is giving me error of invalid invite.

**Comment by akshitagupta15june** [comment]
here is the link https://discord.gg/d5GfFfy8
