### ISSUE TITLE
Feature request(Face detection using MTCNN)

### ISSUE THREAD

**Issue by kuluruvineeth** [akshitagupta15june/Face-X#887]
Wanted to add one more feature for face detection using MTCNN in the code part and enhance the readme with thorough pipeline for the algorithm pictorially and before and after pictures for two application of MTCNN algorithm.

**Comment by akshitagupta15june** [comment]
it is already implemented https://github.com/akshitagupta15june/Face-X/tree/master/Face-Detection/Face%20Detection%20using%20MTCNN
you can enhance the readme
