### ISSUE TITLE
Image Pyramiding using opencv

### ISSUE THREAD

**Issue by sherin527** [akshitagupta15june/Face-X#893]
@akshitagupta15june ma'am, I want to implement Image pyramiding using OpenCV, pls assign this issue to me. I am an LGM-SOC'21 participant.

**Comment by akshitagupta15june** [comment]
Can u tell me more about it?

**Comment by sherin527** [comment]
Image pyramiding is basically a pyramidical representation of the image. It's a kind of resizing or sub-sampling of an image where we can detect an object in that image. So basically it's called a pyramid because the images are arranged in decreasing order of their resolution with a square base.
There are 2 types of pyramids,I want to implement both of these
1.Laplacian pyramid
2.Gaussian pyramid

<img width="281" alt="sample2" src="https://user-images.githubusercontent.com/54814231/121633285-1fade400-caa0-11eb-9a00-102dca072829.PNG">


<img width="438" alt="sample1" src="https://user-images.githubusercontent.com/54814231/121633245-0dcc4100-caa0-11eb-8fe9-098e637d177d.PNG">

**Comment by akshitagupta15june** [comment]
this repository focuses on operations on faces so it will be ok if you take faces image as input and provide your implementation here https://github.com/akshitagupta15june/Face-X/tree/master/Awesome-face-operations this folder contains all the operations that can be performed on faces so you can create a folder name "face-pyramiding" and add our implementation it.
Please provide a proper readme file explaining all your process of pyramiding as well as include output screenshots.

**Comment by Komal-99** [comment]
if @sherin527  is working on  its implementation can i go forward for creating readme for image pyramiding? @akshitagupta15june  as a LGMSOC participant

**Comment by akshitagupta15june** [comment]
i think @Komal-99 you can create a readme after @sherin527 has worked on it .
You can create a new issue after that stating readme

**Comment by Komal-99** [comment]
Okay 👍 @sherin527  is that fine with you

**Comment by sherin527** [comment]
@Komal-99 yes!
