### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by piyush4for** [akshitagupta15june/Face-X#895]
The problem is that all project in this repo use python library that make it slow to recognize face sometime and it require to install library to run it first.

A clear solution is that using chrome API for face detection, we can do face detection easily without requiring any prerequisite to run or use this.

**Comment by piyush4for** [comment]
allow me to add my PR to this issue

**Comment by akshitagupta15june** [comment]
assigning you.
Add your implementation inside face-detection folder

**Comment by piyush4for** [comment]
mam can u plz check the pull request that i made 
https://github.com/akshitagupta15june/Face-X/pull/896#issue-668839526

**Comment by piyush4for** [comment]
plz assist me for any changes in it

**Comment by piyush4for** [comment]
i added again plz check https://github.com/akshitagupta15june/Face-X/pull/901#issue-668909903
