### ISSUE TITLE
Face Recognition Using JavaScript Under LGM-SOC'21 

### ISSUE THREAD

**Issue by KunalSharmaCoder** [akshitagupta15june/Face-X#897]
I want to make a script of Face recognition which every one can use and test in there browser without any additional install.
@akshitagupta15june , Can you assign me this issue under LGM-SOC'21

**Comment by akshitagupta15june** [comment]
ok add your implementation inside face recognition folder

**Comment by piyush4for** [comment]
I think I had done the same previously https://github.com/akshitagupta15june/Face-X/pull/901#issue-668909903. 
So plz check, if not same sorry for bothering
