### ISSUE TITLE
Image pyramiding Readme.md

### ISSUE THREAD

**Issue by Komal-99** [akshitagupta15june/Face-X#899]
**I want to add image pyramiding readme,md including both guasian and laplace  transformation.**
A clear and concise description of what the problem is.

**Describe the documentation you want to improved**

**Additional context**

**Comment by akshitagupta15june** [comment]
assigning you to add your implementation here https://github.com/akshitagupta15june/Face-X/tree/master/Awesome-face-operations/face-pyramiding
