### ISSUE TITLE
Guidelines for NJACK NW'oC Participants.

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#9]
Issues have been raised with labels {"nwoc","beginner","Intermediate","hard"}

If you are familiar with the issue and you can solve it then you can comment there for assigning it to you.

For further queries and discussion please join the discord link mentioned in this repository readme.

Focus of open source programs are to help you learn, grow and develop, please make use of this opportunity.

Very Excited for your Contributions.
Happy Coding!

**Comment by Pranav016** [comment]
I would like to work on this issue.

**Comment by akshitagupta15june** [comment]
this issue is just the guideline
