### ISSUE TITLE
Add links to the badges

### ISSUE THREAD

**Issue by Umesh-01** [akshitagupta15june/Face-X#904]
**Is your documentation request related to a problem? Please describe.**
The badges (see the below image) in the README.md file doesn't contain any link to the related web pages and without them they are of no use.

![image](https://user-images.githubusercontent.com/83420185/121815496-6b28e380-cc94-11eb-809a-10a15b06321a.png)

**Describe the documentation you want to be improved**
I want to  add links to the badges so that anyone can go to the webpages after clicking on them.

**Comment by Umesh-01** [comment]
@akshitagupta15june mam should I work on this??

**Comment by akshitagupta15june** [comment]
hi this is not required because we don't have a webpage to show.

**Comment by Umesh-01** [comment]
@akshitagupta15june mam I think you didn't get what I was saying in this issue...
**For example, if I click on issue badge then it shouldn't take us to this--**

![image](https://user-images.githubusercontent.com/83420185/121816851-a1b62c80-cc9b-11eb-9afd-8985bbd593ae.png)

**Instead we can redirect to the issue web page (see the below image) on github not any external website...
You don't need any website for this...**

![image](https://user-images.githubusercontent.com/83420185/121816901-f5c11100-cc9b-11eb-8519-c979caf76ab8.png)

Please reopen if you want me to assign this issue under LGMSOC... 🙂

**Comment by akshitagupta15june** [comment]
oh ok yeah screenshots explain better assigning you

**Comment by jayant766** [comment]
Assign me plz.
LGM_SOC

**Comment by Umesh-01** [comment]
hello @akshitagupta15june mam, I have done the changes check it out and if u want me to add more badges like closed pr, closed issues, etc. then I will also do that... 

Thanks 🙂
