### ISSUE TITLE
Retro Image Filter

### ISSUE THREAD

**Issue by sherin527** [akshitagupta15june/Face-X#905]
@akshitagupta15june ma'am, I want to implement Retro Image Filter using opencv. pls, assign this issue to me. I am LGM-SOC'21 paticipant.

**Comment by akshitagupta15june** [comment]
can you tell me more about it

**Comment by sherin527** [comment]
![girl](https://user-images.githubusercontent.com/54814231/122163149-531eb300-ce92-11eb-8bf7-72b09e934f68.jpg)
<img width="300"  height="300" alt="image" src="https://user-images.githubusercontent.com/54814231/122163169-59149400-ce92-11eb-91de-55525f9a22fe.PNG">

@akshitagupta15june ma'am I want to add the above filter to an image where the color space will be darker and give a retro feel.

**Comment by akshitagupta15june** [comment]
hi this filter is already implemented
