### ISSUE TITLE
Face Recoginition using VGG16

### ISSUE THREAD

**Issue by keshav340** [akshitagupta15june/Face-X#91]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Comment by hpnightowl** [comment]
can i take this issue ? as am the participant of SWOC 2021

**Comment by akshitagupta15june** [comment]
ok

**Comment by akshitagupta15june** [comment]
Its been late for this issue
closing this one.
