### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by satwiksunnam19** [akshitagupta15june/Face-X#915]
**Problem Statement:** In this busy running world everyone is so busy from the start of the day until we hit the bed. If we take up a case like every day we will go for supermart for bringing up things we will make so fast for checking out things and when we come to our body or face products mainly facewash which we will pick up randomly and use them which leads unknowingly dermal problems so I want to develop a software/ model which can recognize the skin type of the people and recommends the facewash based on skin type.
**Solution:** We will build a Neural Network model(CNN) architecture that classifies the skin types. we will use predefined or URL-based face products which are dedicated to specific types of skin so we can recommend these products to users after classifying the skin type.
**Techologies/ Software used :** TensorFlow, OpenCV.
**Idea of Approach:**  We want to collect the data from the internet of different skin types and we want to use OpenCV haar cascade classifier/ ROI(Region Of Interest) haar cascade classifier for detecting the faces or we will use Region Of Interest for cropping the images manually. We may use the data augmentation for increasing the training data when we have low resources for data then we will create a model which classifies the skin type and we will build a recommendation system.
**Additional Context:** There are around four different skin types 1.Normal skin 2. Oily skin 3. Dry skin 4. Combination Skin
We need at least 100 pictures of each kind of skin type so we can make multiply them using data augmentation techniques.
_Prior information is that at least we can work on two different skin types as we go on can further we can upgrade to further skin types._
![Screenshot (215)](https://user-images.githubusercontent.com/83942187/122637300-76a06280-d10b-11eb-89b3-873346fadc9d.png)

**Comment by akshitagupta15june** [comment]
Ok so you can work on it , try thinking a good name to this implementation so that i can create a new folder and you can add your implementation inside that

**Comment by satwiksunnam19** [comment]
Face Products Recommender system is the name of the project
And I want a discussion form so that it's helpful for others to contribute
and discuss about project

**Comment by satwiksunnam19** [comment]
> Ok so you can work on it , try thinking a good name to this implementation so that i can create a new folder and you can add your implementation inside that

We can name this project as Face Product Recommender system and I want you to create a discussion form so that others can have active contributions

**Comment by akshitagupta15june** [comment]
yeah sure will do the same here is the link of project folder where you can add your implementation by creating a new folder https://github.com/akshitagupta15june/Face-X/tree/master/Face-Product-Recommendation-System
