### ISSUE TITLE
Create one snapchat filters folder.

### ISSUE THREAD

**Issue by saiharsha-22** [akshitagupta15june/Face-X#92]
**Describe the bug**
Instead of having multiple folders for snapchat filters we can have a single folder for snapchat filters and a single images asset folder so that contributors can add on that folder

**Additional details**
If we add a single folder for snap chat filters in future if a person wants to work on GUI for that it will be easy  to create a GUI using those filters.

**Comment by akshitagupta15june** [comment]
OK @saiharsha-22 CAN YOU DO THE SAME

**Comment by saiharsha-22** [comment]
@akshitagupta15june Thank you for assigining the issue. I will try to solve this issue as fast as possible so that contributors can add their, contributioins in snap chat filters section.

**Comment by akshitagupta15june** [comment]
hi @saiharsha-22 i have solved that because i had to change something in that

**Comment by akshitagupta15june** [comment]
thanku for the report you can work on different issue or any issue if you need to add in the project

**Comment by saiharsha-22** [comment]
@akshitagupta15june Ok
