### ISSUE TITLE
Readme Improvement in awesome face operations folder

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#922]
https://github.com/akshitagupta15june/Face-X/tree/master/Awesome-face-operations

**Comment by devanshi-code** [comment]
@akshitagupta15june  what changes need to be done in readme , can you explain!

**Comment by devanshi-code** [comment]
adding images , information or library or any unique idea

**Comment by akshitagupta15june** [comment]
i want this readme to be short and crisp like lots of data is being available for all operations.

**Comment by akshitagupta15june** [comment]
assigned u

**Comment by aryasoni98** [comment]
could i work on this?

**Comment by sarah-nisar** [comment]
I would like to take up this issue.

**Comment by akshitagupta15june** [comment]
ok assigning u
