### ISSUE TITLE
Convert a facial image to a comic image

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#923]
https://github.com/akshitagupta15june/Face-X/tree/master/Cartoonify%20Image

![image](https://user-images.githubusercontent.com/57909583/124342591-8a0afd80-dbe2-11eb-835b-fc69e93bdde5.png)

**Comment by dilroseR** [comment]
i would like to work on this issue
kindly assign it to me

**Comment by akshitagupta15june** [comment]
ok

**Comment by soma2000-lang** [comment]
Can I workon this issue I will be doing it using open -cv
kindly assign
