### ISSUE TITLE
Add a contributors section

### ISSUE THREAD

**Issue by Prakash-Haldar** [akshitagupta15june/Face-X#926]
Add a contributors section in Readme , it will enhance the looks of GitHub  Project
@akshitagupta15june 
it will Shows The profile pic of your Valuable Contributors 

assign this as LGM SOC

**Comment by akshitagupta15june** [comment]
ok

**Comment by Prakash-Haldar** [comment]
@akshitagupta15june I have created The pull request . please see it.
