### ISSUE TITLE
Differentiate cartoon images from real human faces.

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#929]
Differentiate cartoon images from real human faces.

add in cartoony folder

**Comment by soma2000-lang** [comment]
@akshitagupta15june 
I would like to work on this issue kindly assign me this

**Comment by akshitagupta15june** [comment]
Ok

**Comment by yagyesh-bobde** [comment]
should I create a new folder in the main repo ?

**Comment by akshitagupta15june** [comment]
add your folder inside this https://github.com/akshitagupta15june/Face-X/tree/master/Cartoonify-Image

**Comment by yagyesh-bobde** [comment]
kk... thank you

**Comment by yagyesh-bobde** [comment]
can u help me a bit ? like how to approach this

**Comment by akshitagupta15june** [comment]
i will give some resources to get started here are some research papers that you can read https://www.researchgate.net/publication/280978603_Distinguishing_Cartoons_Images_from_Real-Life_Images

**Comment by akshitagupta15june** [comment]
like if we give some images of people as input along with a cartoon image then we have to differentiate

**Comment by yagyesh-bobde** [comment]
kk i'll go through it ..... thank you

**Comment by Basantloay** [comment]
Hello, I would like to work on this issue.

**Comment by akshitagupta15june** [comment]
ok assigning you

**Comment by Salaheldinyoussry** [comment]
Hi , I would like to work on this issue , I think a GAN discriminator model will perform well on this

**Comment by akshitagupta15june** [comment]
Multiple participants can work on this issue so no need of assigning

**Comment by KareemElozeiri** [comment]
I am a GSSOC22 participant, I would like to work on this!

**Comment by akshitagupta15june** [comment]
you can work on it

**Comment by KareemElozeiri** [comment]
Nice

**Comment by akshitagupta15june** [comment]
yes yes @shireenchand you can work on it! I am assigning you
