### ISSUE TITLE
Perform virtual makeover using opencv

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#938]
https://github.com/akshitagupta15june/Face-X/tree/master/Virtual_makeover

![image](https://user-images.githubusercontent.com/57909583/156117790-9c2f1dc9-bf2b-4098-8a50-580c87c1bce9.png)

**Comment by RusJaI** [comment]
I would like to work on this issue for GSSOC-2022

**Comment by akshitagupta15june** [comment]
you can work on this issue and there is no need to assigning as multiple people can contribute in this issue

**Comment by RusJaI** [comment]
Thank you

**Comment by KuberaPrijesh** [comment]
I like to work on this issue.

**Comment by muditchoudhary** [comment]
@KuberaPrijesh I see someone already made a pr for this. I think it should be closed now. @akshitagupta15june should this issue be closed?

**Comment by akshitagupta15june** [comment]
True
