### ISSUE TITLE
3D Face Movements

### ISSUE THREAD

**Issue by aryasoni98** [akshitagupta15june/Face-X#941]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

Controlling 3D character's Face Movements using OpenCV and Python 🐍

It's a python script to control a 3d character's face movements by capturing the user's face landmarks.

First time I am trying to build a 3D Pipeline-- Modeling, animation using OpenCV & Blender Open Source 3D creation suite. Face Movements are not perfect but I’m happy to learn new things.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of the approach to be followed.

**Additional context**

**Comment by aryasoni98** [comment]
Can I start working on it !!!

**Comment by akshitagupta15june** [comment]
Yes
