### ISSUE TITLE
Thanks for sharing my article 

### ISSUE THREAD

**Issue by anushkrishnav** [akshitagupta15june/Face-X#948]
Hey, dropped by to say your project is really cool and very interesting !!
Thank you for sharing my Article 
 [Winter or Summer, Take your baby steps into OpenSource Now !!](https://anush-venkatakrishna.medium.com/part-1-winter-or-summer-take-your-baby-steps-into-opensource-now-7d661235d7ff) with your community.

Good luck

**Comment by akshitagupta15june** [comment]
It's my pleasure @anushkrishnav, a Wonderful article for beginners.
