### ISSUE TITLE
Documentation Improvement in face-x readme

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#956]

**Comment by mehabhalodiya** [comment]
Hey @akshitagupta15june 
Will you please let me know in detail?
I mean, in what way you want modification of the README file?
I would like to contribute.

**Comment by akshitagupta15june** [comment]
Hi!
You can update the  readme with proper content and remove if any grammatical errors.
Add open source org pictures in which this project participated you can take help from labels.
Improve the contributors section if you have some new ideas you can implement. Just let me know

**Comment by khankhushi** [comment]
Hi Akshita, I want to solve this.

**Comment by akshitagupta15june** [comment]
Please mention the open source program in which you are participating

**Comment by khankhushi** [comment]
Hello @akshitagupta15june I am participating in Script Winter of Code.

**Comment by C-Omkar** [comment]
Hi akshita I would like to contribute to this issue, a participant from Codepeak

**Comment by akshitagupta15june** [comment]
as @khankhushi as commented first so i will assign this issue to her! you can look for other issues

**Comment by UdAyAn123** [comment]
I am looking forward to this issue

**Comment by akshitagupta15june** [comment]
Assigning you @UdAyAn123
