### ISSUE TITLE
Add a "what is the day" snapchat filter.

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#957]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of the approach to be followed.

**Additional context**

**Comment by hemanthraj2001** [comment]
Hello @akshitagupta15june ,
what does the "what is the day" filter means?
I'm thinking of adding the day and time on the picture while using the filter? Am I correct?

**Comment by akshitagupta15june** [comment]
you are thinking correct! that is what this issue means.

**Comment by hemanthraj2001** [comment]
> you are thinking correct! that is what this issue means. do u wanna work on this?

could please assign me? I'll try my best to solve this issue!!

**Comment by akshitagupta15june** [comment]
Ok
