### ISSUE TITLE
Add age calculator in realtime filter.

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#958]

**Comment by noobkid2411** [comment]
Hi I would like to contribute to this issue for hacktober 2021,please assign the same to me!

**Comment by iaryangoyal** [comment]
Can i work on this?

**Comment by akshitagupta15june** [comment]
Yes you can

**Comment by yagyesh-bobde** [comment]
May I take this ?
I'm swoc participant
Participant id : 1131

**Comment by akshitagupta15june** [comment]
Yes
