### ISSUE TITLE
Recognition using GhostNet

### ISSUE THREAD

**Issue by Karnak123** [akshitagupta15june/Face-X#97]
**Is your feature request related to a problem? Please describe.**
Create a facial recognition system using GhostNet as the backend model.

**Describe the solution you'd like**
- Create a dataset using OpenCV
- Train a model using GhostNet pretrained weights on PyTorch to recognize different faces
- Implement a lightweight face recognition system live for testing purposes

**Describe alternatives you've considered**
Considered using GhostNet with TensorFlow but model weights are unavailable on TensorFlow, conversion is an option but would be an unnecessary overhead.

**Comment by Karnak123** [comment]
Please assign this issue to me

**Comment by akshitagupta15june** [comment]
sure
