### ISSUE TITLE
Readme updation

### ISSUE THREAD

**Issue by Sloth-Panda** [akshitagupta15june/Face-X#98]
Readme can be updated by adding various open-source programs and gifs

Let me know if this needs to be done

**Comment by akshitagupta15june** [comment]
Hi thankyou!
The open source programs in which this project was part of were 
NWOC
DWOC
SWOC
DSC IIT KALYANI WINTER OF CODE
UACEIT WINTER OF CODE

**Comment by anirudhsai20** [comment]
Please assign me the issue.
