### ISSUE TITLE
Documentation Improvement in liveness detection

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#985]

**Comment by pushkar2112** [comment]
what improvements are to be made in the documentation?
pls specify

**Comment by akshitagupta15june** [comment]
adding more specific information about liveness analysis like adding a flowchart how it works and some more description

**Comment by pushkar2112** [comment]
will the info be provided or we need to do gather it ourselves?

**Comment by akshitagupta15june** [comment]
you can run the code which is present in this repo for knowing how it is working, and also you can gather resources yourself.

**Comment by pushkar2112** [comment]
Please assign this issue to me. I will try my best.

**Comment by akshitagupta15june** [comment]
Sure!

**Comment by yagyesh-bobde** [comment]
can i do this

**Comment by yagyesh-bobde** [comment]
i'm swoc participant
Participant ID : 1131
