### ISSUE TITLE
Add some cool animations (must be related to faces)

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#993]
Think of anything 
Open for discussion
](https://github.com/akshitagupta15june/Face-X/tree/master/Face-X-Animation)

**Comment by dryash213** [comment]
Hello there!
I would like to work on adding facial Animation using GAN's 
Would like to connect 
https://www.linkedin.com/in/yash-kushwaha-543786187/
Do assign me for this task!

**Comment by akshitagupta15june** [comment]
ok assigning u

**Comment by Teju-g49** [comment]
assign me issue
