### ISSUE TITLE
Implement face alignment

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Face-X#997]
https://github.com/akshitagupta15june/Face-X/tree/master/Awesome-face-operations

**Comment by HassanRahim26** [comment]
Hey @akshitagupta15june, I would like to work on this issue. Can you please tell me ways to get started?

**Comment by karnikkanojia** [comment]
Hey, I would like to work on this issue. Can I do it?

**Comment by akshitagupta15june** [comment]
Yes you can
